#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
serial_server: the simcard-server HTTP API, backed by the SIM in a USB serial
(AT command) modem that ModemManager has not claimed, e.g. a phone's ACM port.

Same API as server.py (USIM-https-server compatible, plain HTTP):

  GET /?type=imsi
      -> {"imsi": "311480..."}

  GET /?type=rand-autn&rand=<32 hex>&autn=<32 hex>[&app=isim]
      -> {"res": "<hex>", "ck": "<hex>", "ik": "<hex>"}
      app=isim (an extension, for IMS AKA) runs it on the ISIM, or on the
      USIM if the card has no ISIM.
      On AKA synchronisation failure (AUTS in "res", as SWu-IKEv2 expects):
      -> {"res": "<auts>", "ck": null, "ik": null, "auts": "<28 hex>"}

  GET /?type=apdu&hex=<apdu hex>
      Raw APDU on the USIM (CLA channel bits are set for a logical channel).
      -> {"data": "<hex>", "sw": "9000"}

  GET /?type=imei
      The modem's IMEI (AT+CGSN), an extension for mkconfig.
      -> {"imei": "35..."}

  GET /?type=msisdn
      The SIM's own number (AT+CNUM), else the one given with --msisdn, an
      extension for mkconfig. 404 when there is neither.
      -> {"msisdn": "+1..."}

  GET /?type=isim
      The ISIM's identities (TS 31.103), an extension for mkconfig.
      -> {"impi": "...", "domain": "...", "impu": ["sip:...", "tel:..."]}

APDUs go over a logical channel of our own, next to the modem's basic
channel: opened with AT+CCHO/AT+CGLA (TS 27.007 8.45/8.43) when the modem has
them, else with MANAGE CHANNEL sent through AT+CSIM (Samsung phones). As a
last resort they go over AT+CSIM on the basic channel, re-selecting the USIM
before every operation since the modem moves that channel around too.

    python3 serial_server.py --port /dev/ttyACM0
    python3 serial_server.py --port /dev/serial/by-id/usb-...-if01 --mode csim
    python3 serial_server.py --port /dev/ttyACM0 --probe   # IMSI, then exit

Samsung phones only allow it while the screen is unlocked: the server waits
for an unlock at startup, and requests made while locked fail with a
"phone is locked" error. Developer options > Stay awake keeps it usable.

Needs pyserial and read/write access to the port (root or the tty's group).
The port must not belong to ModemManager: both would talk AT on it at once.
"""
from __future__ import annotations

import argparse
import atexit
import json
import os
import re
import shutil
import signal
import socket
import socketserver
import subprocess
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

import serial

try:
    import termios
    # pyserial raises termios.error (not OSError) once the tty is gone
    PORT_ERRORS = (OSError, serial.SerialException, termios.error)
except ImportError:  # Windows
    PORT_ERRORS = (OSError, serial.SerialException)

USIM_AID_PREFIX = bytes.fromhex("A0000000871002")
ISIM_AID_PREFIX = bytes.fromhex("A0000000871004")

DEFAULT_PORT = "/dev/ttyACM0"
DEFAULT_UNIX_SOCKET = "/run/nekoims/simcard.sock"
AT_TIMEOUT = 10          # seconds per AT command (AUTHENTICATE can be slow)

FINAL_OK = {"OK"}
FINAL_ERROR = re.compile(r"^(ERROR|\+CME ERROR|\+CMS ERROR)", re.I)
LOCKED_ERROR = re.compile(r"PACM\(AP\),NOT_ALLOWED_SLO", re.I)
LOCK_POLL = 2            # seconds between tries while waiting for an unlock


class CardError(Exception):
    pass


class PhoneLocked(CardError):
    """Samsung phones refuse SIM access over AT while the screen is locked
    (+CME Error:PACM(AP),NOT_ALLOWED_SLO; other NOT_ALLOWED codes are
    commands the phone blocks outright, like AT+CGSN)."""


def log(msg: str):
    print(msg, file=sys.stderr, flush=True)


# -- AT port ------------------------------------------------------------------

class AtPort:
    """One AT command at a time on a serial port, reopened if the device
    goes away (a phone re-enumerating after a mode switch)."""

    def __init__(self, path: str):
        self.path = path
        self.ser = None

    def _open(self):
        try:
            self.ser = serial.Serial(self.path, 115200, timeout=0.1)
        except PORT_ERRORS as e:
            raise CardError(f"cannot open {self.path}: {e}")
        for cmd in ("ATE0", "AT+CMEE=2"):
            try:
                self._command(cmd, 2)
            except CardError:
                pass  # not fatal, the parser copes with echo and plain ERROR
            except PORT_ERRORS as e:
                self.close()
                raise CardError(f"{self.path}: {e}")

    def close(self):
        if self.ser:
            try:
                self.ser.close()
            except PORT_ERRORS:
                pass
            self.ser = None

    def _command(self, cmd: str, timeout: float) -> list[str]:
        self.ser.reset_input_buffer()
        self.ser.write((cmd + "\r").encode())
        buf, lines, error = b"", [], None
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            buf += self.ser.read(4096)
            while b"\n" in buf:
                raw, buf = buf.split(b"\n", 1)
                line = raw.decode("ascii", "replace").strip()
                if not line or line == cmd:      # blank or echo
                    continue
                if line in FINAL_OK:
                    if error:
                        raise at_error(cmd, error)
                    return lines
                if FINAL_ERROR.match(line):
                    # Some modems (Samsung) follow +CME ERROR with an OK:
                    # wait a moment for it so it can't answer the next command.
                    error = line
                    deadline = min(deadline, time.monotonic() + 0.3)
                    continue
                lines.append(line)
        if error:
            raise at_error(cmd, error)
        raise CardError(f"{cmd}: no response within {timeout:.0f}s")

    def command(self, cmd: str, timeout: float = AT_TIMEOUT) -> list[str]:
        if not self.ser:
            self._open()
        try:
            return self._command(cmd, timeout)
        except PORT_ERRORS:
            # The device went away; reopen once (same path, ideally by-id).
            self.close()
            self._open()
            try:
                return self._command(cmd, timeout)
            except PORT_ERRORS as e:
                self.close()
                raise CardError(f"{self.path}: {e}")

    def response(self, cmd: str, prefix: str,
                 timeout: float = AT_TIMEOUT) -> str:
        """The value of the "<prefix>: ..." line cmd answers with."""
        for line in self.command(cmd, timeout):
            if line.upper().startswith(prefix.upper() + ":"):
                return line[len(prefix) + 1:].strip()
        raise CardError(f"{cmd}: no {prefix} in the response")


def at_error(cmd: str, error: str) -> CardError:
    if LOCKED_ERROR.search(error):
        return PhoneLocked(f"{cmd}: phone is locked, unlock it ({error})")
    return CardError(f"{cmd}: {error}")


def quoted_hex(value: str, cmd: str) -> bytes:
    m = re.search(r'"([0-9A-Fa-f]*)"', value)
    if not m or len(m.group(1)) % 2:
        raise CardError(f"{cmd}: malformed response {value!r}")
    return bytes.fromhex(m.group(1))


# -- APDU transports ----------------------------------------------------------

class CsimTransport:
    """AT+CSIM on the basic channel. The modem uses this channel itself, so
    every operation starts by selecting the USIM again."""

    name = "AT+CSIM (basic channel)"
    needs_select = True

    def __init__(self, port: AtPort):
        self.port = port

    def cla(self, cla: int) -> int:
        return cla

    def transmit(self, apdu: bytes) -> bytes:
        cmd = f'AT+CSIM={len(apdu) * 2},"{apdu.hex().upper()}"'
        return quoted_hex(self.port.response(cmd, "+CSIM"), "AT+CSIM")

    def close(self):
        pass


def channel_cla(cla: int, n: int) -> int:
    """CLA with logical channel n (ETSI TS 102 221 10.1.1)."""
    if n < 4:
        return (cla & 0xBC) | n
    return (cla & 0xB0) | 0x40 | (n - 4)


class CsimChannelTransport(CsimTransport):
    """A logical channel opened with MANAGE CHANNEL inside AT+CSIM, for
    modems that refuse AT+CCHO and SELECT by AID on the basic channel (e.g.
    Samsung) but pass MANAGE CHANNEL through."""

    needs_select = False

    def __init__(self, port: AtPort):
        super().__init__(port)
        self.session = None

    @property
    def name(self):
        return f"AT+CSIM (logical channel {self.session})"

    def open(self):
        resp = super().transmit(bytes.fromhex("0070000001"))
        if len(resp) != 3 or resp[1:] != b"\x90\x00" or not resp[0]:
            raise CardError(f"MANAGE CHANNEL open returned {resp.hex()}")
        self.session = resp[0]

    def cla(self, cla: int) -> int:
        return channel_cla(cla, self.session or 0)

    def close(self):
        if self.session:
            try:
                super().transmit(bytes([0x00, 0x70, 0x80, self.session, 0x00]))
            except CardError:
                pass
            self.session = None


class CglaTransport:
    """A logical channel opened on the USIM with AT+CCHO, APDUs sent with
    AT+CGLA. The ADF stays selected on it, so no re-selects are needed."""

    needs_select = False

    def __init__(self, port: AtPort, aid: bytes):
        self.port = port
        self.aid = aid
        self.session = None

    @property
    def name(self):
        return f"AT+CGLA (logical channel {self.session})"

    def open(self):
        cmd = f'AT+CCHO="{self.aid.hex().upper()}"'
        lines = self.port.command(cmd)
        for line in lines:
            m = re.match(r"^(?:\+CCHO:\s*)?(\d+)$", line, re.I)
            if m:
                self.session = int(m.group(1))
                return
        raise CardError(f"{cmd}: no session id in {lines!r}")

    def cla(self, cla: int) -> int:
        return channel_cla(cla, self.session or 0)

    def transmit(self, apdu: bytes) -> bytes:
        if self.session is None:
            self.open()
        cmd = (f'AT+CGLA={self.session},{len(apdu) * 2},'
               f'"{apdu.hex().upper()}"')
        try:
            return quoted_hex(self.port.response(cmd, "+CGLA"), "AT+CGLA")
        except PhoneLocked:
            raise
        except CardError:
            # The channel may be gone (modem or SIM reset): open a new one.
            self.close()
            self.open()
            cmd = (f'AT+CGLA={self.session},{len(apdu) * 2},'
                   f'"{apdu.hex().upper()}"')
            return quoted_hex(self.port.response(cmd, "+CGLA"), "AT+CGLA")

    def close(self):
        if self.session is not None:
            try:
                self.port.command(f"AT+CCHC={self.session}", 3)
            except CardError:
                pass
            self.session = None


def tlvs(data: bytes) -> dict:
    """Simple BER-TLV parse (one-byte tags, as in FCPs and ISIM EFs)."""
    out, i = {}, 0
    while i + 1 < len(data):
        tag, n = data[i], data[i + 1]
        i += 2
        if n == 0x81 and i < len(data):
            n, i = data[i], i + 1
        elif n == 0x82 and i + 1 < len(data):
            n, i = int.from_bytes(data[i:i + 2], "big"), i + 2
        out.setdefault(tag, data[i:i + n])
        i += n
    return out


def isim_uri(data: bytes) -> str | None:
    """The 0x80 TLV of an ISIM EF (TS 31.103 4.2.2-4.2.4)."""
    v = tlvs(data).get(0x80)
    return v.decode("utf-8", "replace").strip() if v else None


# -- USIM operations ----------------------------------------------------------

class Usim:
    def __init__(self, port: AtPort, mode: str, aid: bytes | None):
        self.port = port
        self.lock = threading.Lock()
        self.aid = aid
        self.transport = None
        self.no_isim_logged = False
        told = False
        while True:
            try:
                self._connect(mode)
                return
            except PhoneLocked as e:
                if not told:
                    log(f"{e}; waiting (keep the screen unlocked, e.g. "
                        "Developer options > Stay awake)")
                    told = True
                time.sleep(LOCK_POLL)

    def _connect(self, mode: str):
        # The USIM is selected by AID prefix unless --aid says otherwise: the
        # AIDs some modems report through AT+CRSM don't match the card's.
        port = self.port
        errors, locked = [], False
        if mode in ("auto", "cgla"):
            t = CglaTransport(port, self.aid or USIM_AID_PREFIX)
            try:
                t.open()
                self.transport = t
            except CardError as e:
                errors.append(str(e))
                locked = locked or isinstance(e, PhoneLocked)
        if not self.transport and mode in ("auto", "channel"):
            t = CsimChannelTransport(port)
            try:
                t.open()
                try:
                    self.aid = self._select_aid(self.aid or USIM_AID_PREFIX,
                                                "USIM", t)
                except CardError:
                    t.close()
                    raise
                self.transport = t
            except CardError as e:
                errors.append(str(e))
                locked = locked or isinstance(e, PhoneLocked)
        if not self.transport and mode in ("auto", "csim"):
            t = CsimTransport(port)
            try:
                t.transmit(bytes.fromhex("00A40004022F00"))  # SELECT EF.DIR
                self.transport = t
            except CardError as e:
                errors.append(str(e))
                locked = locked or isinstance(e, PhoneLocked)
        if not self.transport:
            msg = "no way to reach the SIM: " + "; ".join(errors)
            raise PhoneLocked(msg) if locked else CardError(msg)

    def close(self):
        if self.transport:
            self.transport.close()

    def _xmit(self, apdu: bytes, transport=None):
        t = transport or self.transport
        apdu = bytes([t.cla(apdu[0])]) + apdu[1:]
        resp = t.transmit(apdu)
        if len(resp) < 2:
            raise CardError(f"short response {resp.hex()!r}")
        data, sw1, sw2 = resp[:-2], resp[-2], resp[-1]
        while sw1 == 0x61:  # response bytes available -> GET RESPONSE
            resp = t.transmit(bytes([t.cla(0x00), 0xC0, 0x00, 0x00, sw2]))
            data, sw1, sw2 = data + resp[:-2], resp[-2], resp[-1]
        if sw1 == 0x6C:     # wrong Le -> resend with the right one
            resp = t.transmit(apdu[:-1] + bytes([sw2]))
            data, sw1, sw2 = resp[:-2], resp[-2], resp[-1]
        return data, sw1, sw2

    def _select_aid(self, aid: bytes, name: str, transport=None) -> bytes:
        """SELECT by (possibly partial) AID; returns the full AID."""
        apdu = bytes([0x00, 0xA4, 0x04, 0x04, len(aid)]) + aid + b"\x00"
        fcp, sw1, sw2 = self._xmit(apdu, transport)
        if sw1 != 0x90:
            raise CardError(f"SELECT {name} failed: SW={sw1:02X}{sw2:02X}")
        return tlvs(fcp[2:] if fcp[:1] == b"\x62" else fcp).get(0x84) or aid

    def _select_usim(self):
        if not self.transport.needs_select:
            return
        self.aid = self._select_aid(self.aid or USIM_AID_PREFIX, "USIM")

    def _read_ef(self, fid: int, transport=None) -> list[bytes]:
        """A transparent EF as one item, or a linear fixed EF's records."""
        fcp, sw1, _ = self._xmit(bytes([0x00, 0xA4, 0x00, 0x04, 0x02]) +
                                 fid.to_bytes(2, "big") + b"\x00", transport)
        if sw1 != 0x90:
            return []
        t = tlvs(fcp[2:] if fcp[:1] == b"\x62" else fcp)
        desc = t.get(0x82, b"")
        if desc[:1] and desc[0] & 0x07 == 0x02 and len(desc) >= 5:
            rec_len, out = int.from_bytes(desc[2:4], "big"), []
            for rec in range(1, desc[4] + 1):
                data, sw1, _ = self._xmit(
                    bytes([0x00, 0xB2, rec, 0x04, rec_len & 0xFF]), transport)
                if sw1 != 0x90:
                    break
                out.append(data)
            return out
        size = min(int.from_bytes(t.get(0x80, b"\x00"), "big") or 255, 255)
        data, sw1, _ = self._xmit(bytes([0x00, 0xB0, 0x00, 0x00, size]),
                                  transport)
        return [data] if sw1 == 0x90 else []

    def isim(self) -> dict:
        """IMPI, home domain and IMPUs from the ISIM (TS 31.103 4.2.2-4)."""
        with self.lock:
            # A channel of its own, so the USIM's stays where it is.
            chan = self._isim_channel()
            try:
                impi = self._read_ef(0x6F02, chan)
                domain = self._read_ef(0x6F03, chan)
                impus = self._read_ef(0x6F04, chan)
            finally:
                if chan:
                    chan.close()
        return {"impi": isim_uri(impi[0]) if impi else None,
                "domain": isim_uri(domain[0]) if domain else None,
                "impu": [u for u in map(isim_uri, impus) if u]}

    def imsi(self) -> str:
        with self.lock:
            self._select_usim()
            _, sw1, sw2 = self._xmit(bytes.fromhex("00A40004026F0700"))
            if sw1 != 0x90:
                raise CardError(f"SELECT EF.IMSI failed: SW={sw1:02X}{sw2:02X}")
            raw, sw1, sw2 = self._xmit(bytes.fromhex("00B0000009"))
        if sw1 != 0x90 or not raw or raw[0] > len(raw) - 1:
            raise CardError(f"READ EF.IMSI failed: SW={sw1:02X}{sw2:02X}")
        digits = "".join(f"{b & 0x0F:x}{b >> 4:x}" for b in raw[1:1 + raw[0]])
        digits = digits[1:].rstrip("f")  # drop the parity nibble and padding
        if not digits.isdigit() or not 14 <= len(digits) <= 15:
            raise CardError(f"implausible IMSI {digits!r}")
        return digits

    def _isim_channel(self):
        """A fresh channel with the ISIM selected, or None for the basic
        channel (then the ISIM is selected on it)."""
        chan = None
        if isinstance(self.transport, CglaTransport):
            chan = CglaTransport(self.port, ISIM_AID_PREFIX)
            chan.open()
            return chan
        if isinstance(self.transport, CsimChannelTransport):
            chan = CsimChannelTransport(self.port)
            chan.open()
        try:
            self._select_aid(ISIM_AID_PREFIX, "ISIM", chan)
        except CardError:
            if chan:
                chan.close()
            raise
        return chan

    def authenticate(self, rand: bytes, autn: bytes,
                     isim: bool = False) -> dict:
        """UMTS AKA (AUTHENTICATE, 3G context), on the ISIM if asked and
        present. Returns hex RES/CK/IK or AUTS."""
        body = bytes([len(rand)]) + rand + bytes([len(autn)]) + autn
        apdu = bytes([0x00, 0x88, 0x00, 0x81, len(body)]) + body + b"\x00"
        with self.lock:
            chan, on_isim = None, False
            if isim:
                try:
                    chan = self._isim_channel()
                    on_isim = True
                except CardError as e:
                    if not self.no_isim_logged:
                        log(f"no ISIM ({e}), IMS AKA runs on the USIM")
                        self.no_isim_logged = True
            try:
                if not on_isim:
                    self._select_usim()
                data, sw1, sw2 = self._xmit(apdu, chan)
            finally:
                if chan:
                    chan.close()

        if sw1 == 0x98 and sw2 == 0x62:
            raise CardError("authentication error: MAC failure (AUTN rejected)")
        if sw1 != 0x90 or not data:
            raise CardError(f"AUTHENTICATE failed: SW={sw1:02X}{sw2:02X}")

        tag, p = data[0], 1
        if tag == 0xDC:  # synchronisation failure
            n = data[p]
            auts = data[p + 1:p + 1 + n].hex()
            # SWu-IKEv2 / USIM-https-server put AUTS in "res" with null CK/IK
            return {"res": auts, "ck": None, "ik": None, "auts": auts}
        if tag != 0xDB:
            raise CardError(f"unexpected AUTHENTICATE response tag {tag:02X}")

        out = {}
        for name in ("res", "ck", "ik"):
            n = data[p]
            out[name] = data[p + 1:p + 1 + n].hex()
            p += 1 + n
        return out

    def imei(self) -> str:
        with self.lock:
            lines = self.port.command("AT+CGSN")
        for line in lines:
            m = re.search(r"\b(\d{15})\b", line)
            if m:
                return m.group(1)
        raise CardError(f"AT+CGSN: no IMEI in {lines!r}")

    def msisdn(self) -> str | None:
        """The first number in AT+CNUM (TS 27.007 7.1), read from EF.MSISDN
        by the modem."""
        try:
            with self.lock:
                lines = self.port.command("AT+CNUM")
        except CardError:
            return None  # e.g. +CME ERROR when the SIM has no EF.MSISDN
        for line in lines:
            m = re.match(r'\+CNUM:\s*(?:"[^"]*")?\s*,\s*"(\+?\d+)"', line)
            if m:
                return m.group(1)
        return None

    def apdu(self, apdu: bytes) -> dict:
        with self.lock:
            self._select_usim()
            data, sw1, sw2 = self._xmit(apdu)
        return {"data": data.hex(), "sw": f"{sw1:02X}{sw2:02X}"}


# -- ModemManager check -------------------------------------------------------

def mm_owner(port: str) -> str | None:
    """The ModemManager modem that has this tty among its ports, if any."""
    if not shutil.which("mmcli"):
        return None
    dev = os.path.basename(os.path.realpath(port))
    try:
        listing = subprocess.run(["mmcli", "-L"], capture_output=True,
                                 text=True, timeout=5).stdout
        for path in re.findall(r"/org/freedesktop/ModemManager1/Modem/\d+",
                               listing):
            info = subprocess.run(["mmcli", "-m", path, "-K"],
                                  capture_output=True, text=True,
                                  timeout=5).stdout
            for line in info.splitlines():
                if line.startswith("modem.generic.ports") and \
                        re.search(rf"\b{re.escape(dev)}\b", line):
                    return path
    except (OSError, subprocess.SubprocessError):
        pass
    return None


# -- HTTP ---------------------------------------------------------------------

def parse_hex(q: dict, name: str, length: int | None = None) -> bytes:
    try:
        value = bytes.fromhex(q[name][0])
    except (KeyError, IndexError, ValueError):
        raise ValueError(f"missing or invalid hex parameter '{name}'")
    if length is not None and len(value) != length:
        raise ValueError(f"'{name}' must be {length} bytes")
    return value


class Handler(BaseHTTPRequestHandler):
    server_version = "NekoIMS-simcard-serial/1.0"
    usim: Usim = None  # set in main()

    def address_string(self):
        return self.client_address[0] if self.client_address else "unix"

    def _reply(self, code: int, obj: dict):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        q = parse_qs(urlparse(self.path).query)
        kind = q.get("type", [""])[0]
        try:
            if kind == "imsi":
                self._reply(200, {"imsi": self.usim.imsi()})
            elif kind == "rand-autn":
                rand = parse_hex(q, "rand", 16)
                autn = parse_hex(q, "autn", 16)
                isim = q.get("app", [""])[0] == "isim"
                self._reply(200, self.usim.authenticate(rand, autn, isim))
            elif kind == "imei":
                self._reply(200, {"imei": self.usim.imei()})
            elif kind == "msisdn":
                msisdn = self.usim.msisdn() or self.msisdn
                if msisdn:
                    self._reply(200, {"msisdn": msisdn})
                else:
                    self._reply(404, {"error": "no MSISDN on the SIM"})
            elif kind == "isim":
                self._reply(200, self.usim.isim())
            elif kind == "apdu":
                apdu = parse_hex(q, "hex")
                if len(apdu) < 4:
                    raise ValueError("APDU shorter than 4 bytes")
                self._reply(200, self.usim.apdu(apdu))
            else:
                self._reply(400, {"error": f"unknown type '{kind}'"})
        except ValueError as e:
            self._reply(400, {"error": str(e)})
        except CardError as e:
            self._reply(502, {"error": str(e)})
        except Exception as e:
            self._reply(503, {"error": f"{type(e).__name__}: {e}"})


class ThreadingUnixHTTPServer(socketserver.ThreadingMixIn,
                              socketserver.UnixStreamServer):
    daemon_threads = True


class ThreadingTCPHTTPServer(socketserver.ThreadingMixIn,
                             socketserver.TCPServer):
    daemon_threads = True
    allow_reuse_address = True


def unix_socket_in_use(path: str) -> bool:
    """Whether another server is accepting on path. Two servers sharing the
    card interleave APDUs (e.g. SELECT failing with 6F00), and starting one
    would unlink the other's socket."""
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.settimeout(1)
        s.connect(path)
        return True
    except OSError:
        return False
    finally:
        s.close()


def make_server(listen: str | None, unix_path: str):
    if listen:
        host, _, port = listen.rpartition(":")
        host = host.strip("[]")
        cls = ThreadingTCPHTTPServer
        if ":" in host:
            cls = type("V6", (ThreadingTCPHTTPServer,),
                       {"address_family": socket.AF_INET6})
        return cls((host, int(port)), Handler), f"http://{listen}"

    os.makedirs(os.path.dirname(unix_path), mode=0o750, exist_ok=True)
    if os.path.exists(unix_path):
        os.unlink(unix_path)
    srv = ThreadingUnixHTTPServer(unix_path, Handler)
    os.chmod(unix_path, 0o660)
    return srv, f"unix:{unix_path}"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--port", default=DEFAULT_PORT,
                    help=f"AT serial port (default: {DEFAULT_PORT}; a "
                         "/dev/serial/by-id path survives re-enumeration)")
    ap.add_argument("--mode", choices=("auto", "cgla", "channel", "csim"),
                    default="auto",
                    help="logical channel with AT+CCHO/CGLA, logical channel "
                         "with MANAGE CHANNEL over AT+CSIM, basic channel "
                         "AT+CSIM, or the first that works (default)")
    ap.add_argument("--aid", default=None,
                    help="USIM AID in hex (default: from EF.DIR)")
    ap.add_argument("--unix", default=DEFAULT_UNIX_SOCKET,
                    help=f"Unix socket path (default: {DEFAULT_UNIX_SOCKET})")
    ap.add_argument("--listen", default=None,
                    help="listen on TCP HOST:PORT instead of the Unix socket")
    ap.add_argument("--force", action="store_true",
                    help="run even if ModemManager has claimed the port")
    ap.add_argument("--msisdn", default=None,
                    help="number for type=msisdn when AT+CNUM has none "
                         "(qmi_netdev.py passes the modem's, from QMI)")
    ap.add_argument("--probe", action="store_true",
                    help="read the IMSI, then exit")
    args = ap.parse_args()

    owner = mm_owner(args.port)
    if owner and not args.force:
        sys.exit(f"{args.port} belongs to ModemManager ({owner}); use "
                 "mm_server.py, or have ModemManager ignore the device "
                 "(udev ID_MM_DEVICE_IGNORE=1)")
    if not args.listen and not args.probe and unix_socket_in_use(args.unix):
        sys.exit(f"another SIM server is already serving {args.unix}")

    port = AtPort(args.port)
    try:
        usim = Usim(port, args.mode,
                    bytes.fromhex(args.aid) if args.aid else None)
    except CardError as e:
        sys.exit(f"cannot use the SIM on {args.port}: {e}")
    except KeyboardInterrupt:
        sys.exit(130)
    atexit.register(port.close)
    atexit.register(usim.close)
    # Run atexit (and so close the logical channel) on SIGTERM too.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    log(f"{args.port}: {usim.transport.name}"
        + (f", USIM AID {usim.aid.hex()}" if usim.aid else ""))
    try:
        while True:
            try:
                log(f"USIM IMSI: {usim.imsi()}")
                break
            except PhoneLocked as e:
                log(f"{e}; waiting")
                time.sleep(LOCK_POLL)
    except CardError as e:
        sys.exit(f"cannot read the USIM on {args.port}: {e}")
    if args.probe:
        log("probe OK")
        return

    Handler.usim = usim
    Handler.msisdn = args.msisdn
    try:
        srv, where = make_server(args.listen, args.unix)
    except OSError as e:
        sys.exit(f"cannot listen: {e}")
    log(f"simcard-server (serial) listening on {where}")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        srv.server_close()
        if not args.listen and os.path.exists(args.unix):
            os.unlink(args.unix)


if __name__ == "__main__":
    main()
