#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
simcard-server: a USIM-https-server compatible HTTP service backed by PC/SC.

API (compatible with https://github.com/fasferraz/USIM-https-server, plain HTTP):

  GET /?type=imsi
      -> {"imsi": "311480..."}

  GET /?type=rand-autn&rand=<32 hex>&autn=<32 hex>[&app=isim]
      -> {"res": "<hex>", "ck": "<hex>", "ik": "<hex>"}
      app=isim (an extension, for IMS AKA) runs it on the ISIM, or on the
      USIM if the card has no ISIM.
      On AKA synchronisation failure (AUTS in "res", as SWu-IKEv2 expects;
      "auts" is an extension):
      -> {"res": "<auts>", "ck": null, "ik": null, "auts": "<28 hex>"}

  GET /?type=apdu&hex=<apdu hex>
      Raw APDU passthrough on the currently selected application.
      -> {"data": "<hex>", "sw": "9000"}

Errors return HTTP 4xx/5xx with {"error": "..."}.

By default it listens on a filesystem Unix socket so a client inside another
network namespace (e.g. the `ims` netns created by the ePDG dialer) can reach it
without a loopback interface or veth pair.

    sudo python3 server.py                               # /run/nekoims/simcard.sock
    sudo python3 server.py --listen 127.0.0.1:8888       # TCP instead

On Windows (no AF_UNIX in Python there) it listens on TCP 127.0.0.1:8888 by
default, which is what NekoIMS and the dialer expect there.
    curl --unix-socket /run/nekoims/simcard.sock 'http://sim/?type=imsi'

Requires pyscard and a running pcscd.
"""
from __future__ import annotations

import argparse
import json
import os
import socket
import socketserver
import sys
import threading
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

from smartcard.System import readers

USIM_AID_PREFIX = bytes.fromhex("A0000000871002")
ISIM_AID_PREFIX = bytes.fromhex("A0000000871004")

DEFAULT_UNIX_SOCKET = "/run/nekoims/simcard.sock"
DEFAULT_TCP = "127.0.0.1:8888"  # where there is no AF_UNIX (Windows)
HAVE_UNIX = hasattr(socket, "AF_UNIX")


class CardError(Exception):
    pass


class Usim:
    """Serialised access to the USIM application on one PC/SC reader."""

    def __init__(self, reader_index: int):
        self.reader_index = reader_index
        self.lock = threading.Lock()

    # -- low level ---------------------------------------------------------

    def _connect(self):
        rlist = readers()
        if not rlist:
            raise CardError("no PC/SC readers")
        if self.reader_index >= len(rlist):
            raise CardError(f"reader index {self.reader_index} out of range "
                            f"({len(rlist)} readers)")
        conn = rlist[self.reader_index].createConnection()
        conn.connect()
        return conn

    @staticmethod
    def _xmit(conn, apdu: bytes):
        data, sw1, sw2 = conn.transmit(list(apdu))
        while sw1 == 0x61:  # response bytes available -> GET RESPONSE
            more, sw1, sw2 = conn.transmit([0x00, 0xC0, 0x00, 0x00, sw2])
            data = data + more
        if sw1 == 0x6C:     # wrong Le -> resend with the right one
            data, sw1, sw2 = conn.transmit(list(apdu[:-1]) + [sw2])
        return bytes(data), sw1, sw2

    def _select_usim(self, conn):
        """Find the USIM AID in EF.DIR and SELECT it (TS 31.102)."""
        self._select_app(conn, USIM_AID_PREFIX, "USIM")

    def _select_app(self, conn, aid_prefix: bytes, name: str):
        """SELECT the first EF.DIR application whose AID starts with
        aid_prefix (USIM, or ISIM for TS 31.103)."""
        self._xmit(conn, bytes([0x00, 0xA4, 0x00, 0x04, 0x02, 0x2F, 0x00]))
        for rec in range(1, 16):
            data, sw1, _ = self._xmit(conn, bytes([0x00, 0xB2, rec, 0x04, 0x00]))
            if sw1 != 0x90:
                break
            i = data.find(0x4F)  # AID tag inside the 0x61 application template
            if i < 0 or i + 1 >= len(data):
                continue
            aid = data[i + 2:i + 2 + data[i + 1]]
            if aid.startswith(aid_prefix):
                apdu = bytes([0x00, 0xA4, 0x04, 0x04, len(aid)]) + aid + b"\x00"
                _, sw1, sw2 = self._xmit(conn, apdu)
                if sw1 != 0x90:
                    raise CardError(f"SELECT {name} failed: SW={sw1:02X}{sw2:02X}")
                return
        raise CardError(f"no {name} application found in EF.DIR")

    def _read_ef(self, conn, fid: bytes, length: int) -> bytes:
        apdu = bytes([0x00, 0xA4, 0x00, 0x04, len(fid)]) + fid + b"\x00"
        _, sw1, sw2 = self._xmit(conn, apdu)
        if sw1 != 0x90:
            raise CardError(f"SELECT {fid.hex()} failed: SW={sw1:02X}{sw2:02X}")
        data, sw1, sw2 = self._xmit(conn, bytes([0x00, 0xB0, 0x00, 0x00, length]))
        if sw1 != 0x90:
            raise CardError(f"READ BINARY failed: SW={sw1:02X}{sw2:02X}")
        return data

    # -- operations --------------------------------------------------------

    def imsi(self) -> str:
        with self.lock:
            conn = self._connect()
            try:
                self._select_usim(conn)
                raw = self._read_ef(conn, b"\x6F\x07", 9)  # EF.IMSI
            finally:
                conn.disconnect()
        if not raw or raw[0] > len(raw) - 1:
            raise CardError("malformed EF.IMSI")
        digits = "".join(f"{b & 0x0F:x}{b >> 4:x}" for b in raw[1:1 + raw[0]])
        digits = digits[1:].rstrip("f")  # drop the parity nibble and padding
        if not digits.isdigit() or not 14 <= len(digits) <= 15:
            raise CardError(f"implausible IMSI {digits!r}")
        return digits

    def authenticate(self, rand: bytes, autn: bytes,
                     isim: bool = False) -> dict:
        """UMTS AKA (AUTHENTICATE, 3G context), on the ISIM if asked and
        present. Returns hex RES/CK/IK or AUTS."""
        body = bytes([len(rand)]) + rand + bytes([len(autn)]) + autn
        apdu = bytes([0x00, 0x88, 0x00, 0x81, len(body)]) + body + b"\x00"
        with self.lock:
            conn = self._connect()
            try:
                try:
                    if not isim:
                        raise CardError("USIM asked for")
                    self._select_app(conn, ISIM_AID_PREFIX, "ISIM")
                except CardError:
                    self._select_usim(conn)
                data, sw1, sw2 = self._xmit(conn, apdu)
            finally:
                conn.disconnect()

        if sw1 == 0x98 and sw2 == 0x62:
            raise CardError("authentication error: MAC failure (AUTN rejected)")
        if sw1 != 0x90 or not data:
            raise CardError(f"AUTHENTICATE failed: SW={sw1:02X}{sw2:02X}")

        tag, p = data[0], 1
        if tag == 0xDC:  # synchronisation failure
            n = data[p]
            auts = data[p + 1:p + 1 + n].hex()
            # SWu-IKEv2 / USIM-https-server put AUTS in "res" with null CK/IK
            return {"res": auts, "ck": None, "ik": None, "auts": auts}
        if tag != 0xDB:
            raise CardError(f"unexpected AUTHENTICATE response tag {tag:02X}")

        out = {}
        for name in ("res", "ck", "ik"):
            n = data[p]
            out[name] = data[p + 1:p + 1 + n].hex()
            p += 1 + n
        return out

    def apdu(self, apdu: bytes) -> dict:
        with self.lock:
            conn = self._connect()
            try:
                self._select_usim(conn)
                data, sw1, sw2 = self._xmit(conn, apdu)
            finally:
                conn.disconnect()
        return {"data": data.hex(), "sw": f"{sw1:02X}{sw2:02X}"}


def parse_hex(q: dict, name: str, length: int | None = None) -> bytes:
    try:
        value = bytes.fromhex(q[name][0])
    except (KeyError, IndexError, ValueError):
        raise ValueError(f"missing or invalid hex parameter '{name}'")
    if length is not None and len(value) != length:
        raise ValueError(f"'{name}' must be {length} bytes")
    return value


class Handler(BaseHTTPRequestHandler):
    server_version = "NekoIMS-simcard/1.0"
    usim: Usim = None  # set in main()

    def address_string(self):
        # Unix socket peers have no (host, port) tuple.
        return self.client_address[0] if self.client_address else "unix"

    def _reply(self, code: int, obj: dict):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        q = parse_qs(urlparse(self.path).query)
        kind = q.get("type", [""])[0]
        try:
            if kind == "imsi":
                self._reply(200, {"imsi": self.usim.imsi()})
            elif kind == "rand-autn":
                rand = parse_hex(q, "rand", 16)
                autn = parse_hex(q, "autn", 16)
                isim = q.get("app", [""])[0] == "isim"
                self._reply(200, self.usim.authenticate(rand, autn, isim))
            elif kind == "apdu":
                self._reply(200, self.usim.apdu(parse_hex(q, "hex")))
            else:
                self._reply(400, {"error": f"unknown type '{kind}'"})
        except ValueError as e:
            self._reply(400, {"error": str(e)})
        except CardError as e:
            self._reply(502, {"error": str(e)})
        except Exception as e:  # pyscard raises a zoo of exception types
            self._reply(503, {"error": f"{type(e).__name__}: {e}"})


if HAVE_UNIX:
    class ThreadingUnixHTTPServer(socketserver.ThreadingMixIn,
                                  socketserver.UnixStreamServer):
        daemon_threads = True


class ThreadingTCPHTTPServer(socketserver.ThreadingMixIn,
                             socketserver.TCPServer):
    daemon_threads = True
    # SO_REUSEADDR on Windows lets another process bind the same port, so a
    # second server would take requests meant for this one.
    allow_reuse_address = sys.platform != "win32"


def unix_socket_in_use(path: str) -> bool:
    """Whether another server is accepting on path. Two servers sharing the
    card interleave APDUs (e.g. SELECT failing with 6F00), and starting one
    would unlink the other's socket."""
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.settimeout(1)
        s.connect(path)
        return True
    except OSError:
        return False
    finally:
        s.close()


def make_server(listen: str | None, unix_path: str):
    if listen:
        host, _, port = listen.rpartition(":")
        host = host.strip("[]")
        cls = ThreadingTCPHTTPServer
        if ":" in host:
            cls = type("V6", (ThreadingTCPHTTPServer,),
                       {"address_family": socket.AF_INET6})
        return cls((host, int(port)), Handler), f"http://{listen}"

    os.makedirs(os.path.dirname(unix_path), mode=0o750, exist_ok=True)
    if os.path.exists(unix_path):
        os.unlink(unix_path)
    srv = ThreadingUnixHTTPServer(unix_path, Handler)
    os.chmod(unix_path, 0o660)
    return srv, f"unix:{unix_path}"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--reader", type=int, default=0, help="PC/SC reader index")
    ap.add_argument("--unix", default=DEFAULT_UNIX_SOCKET,
                    help=f"Unix socket path (default: {DEFAULT_UNIX_SOCKET})")
    ap.add_argument("--listen", default=None if HAVE_UNIX else DEFAULT_TCP,
                    help="listen on TCP HOST:PORT instead of the Unix socket"
                         + ("" if HAVE_UNIX else f" (default: {DEFAULT_TCP})"))
    args = ap.parse_args()
    if not args.listen and unix_socket_in_use(args.unix):
        sys.exit(f"another SIM server is already serving {args.unix}")

    Handler.usim = Usim(args.reader)
    try:
        print(f"USIM IMSI: {Handler.usim.imsi()}", file=sys.stderr)
    except Exception as e:
        sys.exit(f"cannot read the USIM on reader {args.reader}: {e}")

    srv, where = make_server(args.listen, args.unix)
    print(f"simcard-server listening on {where}", file=sys.stderr)
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        srv.server_close()
        if not args.listen and os.path.exists(args.unix):
            os.unlink(args.unix)


if __name__ == "__main__":
    main()
