#!/usr/bin/env bash
# This file is entirely generated by Artificial Intelligence (AI). License may be vague.
#
# start.sh: build NekoIMS if needed, start the SIM server for whatever SIM is
# attached (PC/SC reader or ModemManager modem), write the config, dial the
# ePDG with the static strongSwan build and run NekoIMS in the tunnel netns.
#
#   ./start.sh [options] [-- nekoims args...]
#
#   --sim pcsc|mm|server
#                     SIM backend (default: autodetect, PC/SC reader first,
#                     else a SIM server already on the socket, e.g. a
#                     serial_server.py started by hand)
#   --reader N        PC/SC reader index (pcsc)
#   --modem M         ModemManager modem index, path or IMEI (mm)
#   --config PATH     NekoIMS config (default: generated from the SIM by
#                     mkconfig)
#   --remote URL      static strongSwan tarball for the dialer, {arch} expands
#                     to x86_64/arm64 (default: latest neko-strongswan release)
#   --charon PATH     use an installed charon instead of --remote
#   --rebuild         rebuild NekoIMS even if build/nekoims exists
#   --watch           restart NekoIMS (keeping the tunnel) whenever
#                     build/nekoims changes, and copy its and the dialer's
#                     output to build/ (readable without root)
#
# Everything after -- goes to nekoims (e.g. -- -v -t). Ctrl-C or quitting
# NekoIMS hangs up the tunnel and stops what this script started.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BUILD=$REPO/build
if [ "$(uname -s)" = Darwin ]; then RUN_DIR=/var/run/nekoims; else RUN_DIR=/run/nekoims; fi
SOCK=$RUN_DIR/simcard.sock
PCSCF_FILE=$RUN_DIR/pcscf
NETNS=ims
REMOTE_DEFAULT='https://github.com/MercuryWorkshop/neko-strongswan/releases/latest/download/linux-strongswan-{arch}.tar.gz'
DIAL_TIMEOUT=90

SIM=auto READER= MODEM= CONFIG= REMOTE= CHARON= REBUILD=0 WATCH=0
NEKOIMS_ARGS=()
SUDO_ARGS=()  # our arguments minus --rebuild, for the re-run under sudo
for a in "$@"; do [ "$a" = --rebuild ] || SUDO_ARGS+=("$a"); done

die() { echo "start.sh: $*" >&2; exit 1; }
log() { echo "start.sh: $*" >&2; }

while [ $# -gt 0 ]; do
	case $1 in
		--sim)		SIM=${2:?}; shift ;;
		--reader)	READER=${2:?}; shift ;;
		--modem)	MODEM=${2:?}; shift ;;
		--config)	CONFIG=${2:?}; shift ;;
		--remote)	REMOTE=${2:?}; shift ;;
		--charon)	CHARON=${2:?}; shift ;;
		--rebuild)	REBUILD=1 ;;
		--watch)	WATCH=1 ;;
		--)			shift; NEKOIMS_ARGS=("$@"); break ;;
		-h|--help)	sed -n '4,27p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*)			die "unknown option $1 (see --help)" ;;
	esac
	shift
done
case $SIM in auto|pcsc|mm|server) ;; *) die "--sim must be pcsc, mm or server" ;; esac
[ -n "$REMOTE" ] && [ -n "$CHARON" ] && die "--remote and --charon are exclusive"

# -- 1. build (as the invoking user, never as root) ---------------------------

if [ ! -x "$BUILD/nekoims" ] || [ "$REBUILD" = 1 ]; then
	command -v cmake >/dev/null || die "cmake not found"
	AS_USER=()
	if [ "$(id -u)" = 0 ] && [ -n "${SUDO_USER:-}" ]; then
		AS_USER=(sudo -u "$SUDO_USER" --)
	fi
	log "building NekoIMS"
	if [ ! -f "$BUILD/CMakeCache.txt" ]; then
		"${AS_USER[@]}" cmake -S "$REPO" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release
	fi
	"${AS_USER[@]}" cmake --build "$BUILD" -j"$(nproc)"
fi
[ -x "$BUILD/nekoims" ] || die "build did not produce $BUILD/nekoims"

if [ "$(id -u)" != 0 ]; then
	log "root needed for the SIM server, tunnel and netns, re-running with sudo"
	exec sudo -- "$0" "${SUDO_ARGS[@]}"
fi

# -- cleanup ------------------------------------------------------------------

SIM_PID= DIAL_PID= TAIL_PID=
cleanup() {
	trap - EXIT INT TERM
	[ -z "$TAIL_PID" ] || kill "$TAIL_PID" 2>/dev/null || true
	if [ -n "$DIAL_PID" ] && kill -0 "$DIAL_PID" 2>/dev/null; then
		log "hanging up the ePDG tunnel"
		kill -TERM "$DIAL_PID" 2>/dev/null || true
		wait "$DIAL_PID" 2>/dev/null || true
	fi
	if [ -n "$SIM_PID" ] && kill -0 "$SIM_PID" 2>/dev/null; then
		kill -TERM "$SIM_PID" 2>/dev/null || true
		wait "$SIM_PID" 2>/dev/null || true
	fi
}
trap cleanup EXIT
trap 'exit 130' INT TERM

mkdir -p "$RUN_DIR"
chmod 750 "$RUN_DIR"

# One start.sh at a time. Children get fd 9 closed so leftovers can't hold it.
exec 9>"$RUN_DIR/start.lock"
flock -n 9 || die "another start.sh is already running"

# Processes a previous run left behind (e.g. its terminal was killed). A second
# dialer would fight over charon, a second SIM server over the card.
leftovers() { pgrep -f "$REPO/$1" | tr '\n' ' ' || true; }
DIALERS=$(leftovers 'dialers/strongswan-dialer\.py')
[ -z "$DIALERS" ] || die "a dialer is already running (pid $DIALERS), stop it: sudo kill $DIALERS"

# -- 2. SIM server ------------------------------------------------------------

sim_up() {
	python3 - "$SOCK" <<'EOF' 2>/dev/null
import http.client, socket, sys
class C(http.client.HTTPConnection):
    def connect(self):
        self.sock = socket.socket(socket.AF_UNIX)
        self.sock.settimeout(5)
        self.sock.connect(sys.argv[1])
c = C("sim")
c.request("GET", "/?type=imsi")
sys.exit(0 if c.getresponse().status == 200 else 1)
EOF
}

have_pcsc() {  # a reader with a card in it
	python3 - <<'EOF' 2>/dev/null
import sys
from smartcard.System import readers
for r in readers():
    try:
        c = r.createConnection()
        c.connect()
        c.disconnect()
        sys.exit(0)
    except Exception as e:
        print(e)
sys.exit(1)
EOF
}

have_mm() {
	command -v mmcli >/dev/null || return 1
	local m
	for m in $(mmcli -L 2>/dev/null | grep -o '/org/freedesktop/ModemManager1/Modem/[0-9]*'); do
		mmcli -m "$m" -K 2>/dev/null |
			grep -qE '^modem\.generic\.sim +: /org/freedesktop/ModemManager1/SIM/' &&
			return 0
	done
	return 1
}

if [ "$SIM" = auto ]; then
	if have_pcsc; then
		SIM=pcsc
		have_mm && log "ModemManager also has a SIM; using PC/SC, pass --sim mm for the modem"
	elif have_mm; then
		SIM=mm
	elif sim_up; then
		SIM=server
	else
		die "no SIM found: no PC/SC reader (pcscd + pyscard) and no ModemManager modem with a SIM"
	fi
fi
log "SIM backend: $SIM"

if sim_up; then
	log "reusing the SIM server already on $SOCK"
elif [ "$SIM" = server ]; then
	die "no SIM server answering on $SOCK (start one, e.g. simcard-server/serial_server.py)"
else
	SERVERS=$(leftovers 'simcard-server/(server|mm_server)\.py')
	[ -z "$SERVERS" ] || die "a SIM server is running (pid $SERVERS) but not \
answering on $SOCK, stop it: sudo kill $SERVERS"
	if [ "$SIM" = pcsc ]; then
		python3 "$REPO/simcard-server/server.py" ${READER:+--reader "$READER"} 9>&- &
	else
		python3 "$REPO/simcard-server/mm_server.py" ${MODEM:+--modem "$MODEM"} 9>&- &
	fi
	SIM_PID=$!
	for _ in $(seq 50); do
		sim_up && break
		kill -0 "$SIM_PID" 2>/dev/null || die "SIM server exited"
		sleep 0.2
	done
	sim_up || die "SIM server did not come up on $SOCK"
fi

# -- 3. config ----------------------------------------------------------------

DIALER_HINTS=()  # --epdg/--mnc-len that mkconfig learned from the SIM and DNS
if [ -z "$CONFIG" ]; then
	CONFIG=$RUN_DIR/config.json
	HINTS_FILE=$RUN_DIR/dialer.args
	log "generating $CONFIG with mkconfig"
	if [ "$SIM" = mm ]; then
		SIM_SEL=(--sim mm ${MODEM:+--modem "$MODEM"})
	elif [ "$SIM" = server ]; then
		SIM_SEL=(--sim server --simcard-server "unix:$SOCK")
	else
		SIM_SEL=(--sim pcsc ${READER:+--reader "$READER"})
	fi
	python3 "$REPO/tools/mkconfig.py" "${SIM_SEL[@]}" -o "$CONFIG" --force \
		--dialer-args "$HINTS_FILE" 9>&- || die "mkconfig failed"
	mapfile -t DIALER_HINTS <"$HINTS_FILE"
fi
[ -f "$CONFIG" ] || die "config $CONFIG not found"
if python3 -c 'import json, sys; sys.exit(0 if json.load(open(sys.argv[1])).get("pcscf") else 1)' \
	"$CONFIG" 2>/dev/null; then
	log "warning: $CONFIG sets \"pcscf\", which overrides the one the ePDG assigns"
fi

# -- 4. dial ------------------------------------------------------------------

DIAL_ARGS=("${DIALER_HINTS[@]}")
if [ -n "$CHARON" ]; then
	DIAL_ARGS+=(--charon "$CHARON")
else
	DIAL_ARGS+=(--remote "${REMOTE:-$REMOTE_DEFAULT}")
fi
DIAL_LOG=$RUN_DIR/dialer.log
rm -f "$PCSCF_FILE"
log "dialing the ePDG (log: $DIAL_LOG)"
python3 "$REPO/dialers/strongswan-dialer.py" "${DIAL_ARGS[@]}" >"$DIAL_LOG" 2>&1 9>&- &
DIAL_PID=$!

for _ in $(seq $((DIAL_TIMEOUT * 5))); do
	[ -s "$PCSCF_FILE" ] && break
	if ! kill -0 "$DIAL_PID" 2>/dev/null; then
		tail -n 25 "$DIAL_LOG" >&2
		die "dialer exited before the tunnel came up"
	fi
	sleep 0.2
done
if [ ! -s "$PCSCF_FILE" ]; then
	tail -n 25 "$DIAL_LOG" >&2
	die "no P-CSCF from the ePDG after ${DIAL_TIMEOUT}s"
fi
grep -E '^tunnel up' "$DIAL_LOG" >&2 || true
log "P-CSCF: $(head -n1 "$PCSCF_FILE")"

# -- 5. NekoIMS ---------------------------------------------------------------

# NekoIMS registers over the tunnel it started on. When the dialer redials
# (new address, maybe a new P-CSCF; it replaces $PCSCF_FILE, and removes it
# while down) NekoIMS is restarted once the new tunnel is up. With --watch a
# rebuild of build/nekoims (as the normal user) restarts it too, and its
# output and the dialer's are copied to build/ (readable without root).
# Quitting NekoIMS from its console or Ctrl-C ends the script.
tunnel_id() { stat -c '%i.%Y' "$PCSCF_FILE" 2>/dev/null || echo none; }
mtime() { stat -c %Y "$BUILD/nekoims" 2>/dev/null || echo 0; }
REASON_FILE=$RUN_DIR/restart.reason

if [ "$WATCH" = 1 ]; then
	NEKO_LOG=$BUILD/nekoims.log
	[ -s "$NEKO_LOG" ] && mv -f "$NEKO_LOG" "$NEKO_LOG.1"  # the previous run's
	: >"$NEKO_LOG"
	: >"$BUILD/dialer.log"
	if [ -n "${SUDO_USER:-}" ]; then
		chown "$SUDO_USER" "$NEKO_LOG" "$BUILD/dialer.log"
	fi
	tail -n +1 -F "$DIAL_LOG" >>"$BUILD/dialer.log" 2>/dev/null 9>&- &
	TAIL_PID=$!
fi

while :; do
	for _ in $(seq $((DIAL_TIMEOUT * 5))); do
		[ -s "$PCSCF_FILE" ] && break
		kill -0 "$DIAL_PID" 2>/dev/null || die "dialer exited"
		sleep 0.2
	done
	[ -s "$PCSCF_FILE" ] || die "no tunnel after ${DIAL_TIMEOUT}s"
	STAMP=$(mtime) TUNNEL=$(tunnel_id)
	rm -f "$REASON_FILE"

	# Watcher: SIGINT (clean deregistration, if the network is still
	# there) on a new build or a new tunnel.
	(
		while sleep 2; do
			if [ "$WATCH" = 1 ] && [ "$(mtime)" != "$STAMP" ]; then
				echo build >"$REASON_FILE"
				sleep 2  # let the linker finish
			elif [ "$(tunnel_id)" != "$TUNNEL" ]; then
				echo tunnel >"$REASON_FILE"
			else
				continue
			fi
			pkill -INT -f "^$BUILD/nekoims -c " || true
			break
		done
	) 9>&- &
	WATCH_PID=$!

	set +e
	if [ "$WATCH" = 1 ]; then
		log "starting NekoIMS in netns $NETNS (log: $NEKO_LOG)"
		echo "=== start.sh: NekoIMS started $(date '+%F %T') ===" >>"$NEKO_LOG"
		# script(1): NekoIMS keeps a terminal (line-buffered output,
		# console input) while everything is flushed to the log.
		CMD=$(printf '%q ' ip netns exec "$NETNS" "$BUILD/nekoims" \
			-c "$CONFIG" "${NEKOIMS_ARGS[@]}")
		script -q -f -e -a -c "$CMD" "$NEKO_LOG" 9>&-
	else
		log "starting NekoIMS in netns $NETNS"
		ip netns exec "$NETNS" "$BUILD/nekoims" -c "$CONFIG" \
			"${NEKOIMS_ARGS[@]}" 9>&-
	fi
	RC=$?
	set -e
	kill "$WATCH_PID" 2>/dev/null || true
	wait "$WATCH_PID" 2>/dev/null || true

	REASON=$(cat "$REASON_FILE" 2>/dev/null || true)
	rm -f "$REASON_FILE"
	case $REASON in
		build)	MSG="build/nekoims changed" ;;
		tunnel)	MSG="the ePDG tunnel changed" ;;
		*)	exit "$RC" ;;
	esac
	log "$MSG, restarting NekoIMS"
	[ "$WATCH" = 0 ] ||
		echo "=== start.sh: restarting, $MSG ===" >>"$NEKO_LOG"
	sleep 1
done
