# This file is entirely generated by Artificial Intelligence (AI). License may be vague.
#
# start.ps1: the Windows counterpart of start.sh. Builds NekoIMS if needed,
# starts the SIM server (or uses one already running), writes the config,
# dials the ePDG with the Windows build of neko-strongswan (charon-svc,
# kernel-libipsec on a Wintun adapter) and runs NekoIMS over the tunnel.
#
#   .\start.ps1 [options] [-- nekoims args...]
#
#   -Sim pcsc|server  SIM backend (default: a SIM server already answering on
#                     -SimServer, else the PC/SC reader)
#   -Reader N         PC/SC reader index (pcsc)
#   -SimServer URL    SIM server to use or start (default:
#                     http://127.0.0.1:8888), e.g. http://host:5309 for a
#                     simcard-server on another machine
#   -Config PATH      NekoIMS config (default: generated from the SIM by
#                     mkconfig)
#   -Remote URL       strongSwan zip for the dialer, {arch} expands to
#                     x86_64/arm64 (default: latest neko-strongswan release)
#   -Charon PATH      use an unpacked charon-svc.exe instead of -Remote
#   -Rebuild          rebuild NekoIMS even if it is already built
#
# Everything after -- goes to nekoims (e.g. -- -v -t). Needs Administrator
# (Wintun adapter, routes, firewall), it re-runs itself elevated after the
# build. Ctrl-C or quitting NekoIMS hangs up the tunnel and stops what this
# script started.
[CmdletBinding(PositionalBinding = $false)]
param(
    [ValidateSet("auto", "pcsc", "server")] [string] $Sim = "auto",
    [int] $Reader = -1,
    [string] $SimServer = "http://127.0.0.1:8888",
    [string] $Config = "",
    [string] $Remote = "",
    [string] $Charon = "",
    [switch] $Rebuild,
    [Parameter(ValueFromRemainingArguments = $true)] [string[]] $NekoArgs
)

$ErrorActionPreference = "Stop"
$Repo = $PSScriptRoot
$Build = Join-Path $Repo "build"
$RunDir = Join-Path $env:ProgramData "NekoIMS"
$PcscfFile = Join-Path $RunDir "pcscf"
$RemoteDefault = "https://github.com/MercuryWorkshop/neko-strongswan/releases/latest/download/windows-strongswan-{arch}.zip"
$DialTimeout = 90
if ($NekoArgs -and $NekoArgs[0] -eq "--") { $NekoArgs = $NekoArgs[1..($NekoArgs.Count)] }
if (-not $NekoArgs) { $NekoArgs = @() }

function Log($msg) { [Console]::Error.WriteLine("start.ps1: $msg") }
function Die($msg) { Log $msg; exit 1 }

if ($Remote -and $Charon) { Die "-Remote and -Charon are exclusive" }

function Find-Python {
    foreach ($p in @("python", "py")) {
        $c = Get-Command $p -ErrorAction SilentlyContinue
        if ($c) { return $c.Source }
    }
    Die "Python 3 not found"
}
$Python = Find-Python

function Find-Nekoims {
    foreach ($p in @("nekoims.exe", "Release\nekoims.exe", "RelWithDebInfo\nekoims.exe")) {
        $f = Join-Path $Build $p
        if (Test-Path $f) { return $f }
    }
    return $null
}

# -- 1. build (not elevated) ---------------------------------------------------

function Invoke-Build {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) { Die "Visual Studio (C++ workload) not found" }
    $vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.ARM64 Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if (-not $vs) { $vs = & $vswhere -latest -products * -property installationPath }
    $vcvars = Join-Path $vs "VC\Auxiliary\Build\vcvarsall.bat"
    $arch = if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64" -or $env:PROCESSOR_ARCHITEW6432 -eq "ARM64" -or
                (Get-CimInstance Win32_Processor).Architecture -eq 12) { "arm64" } else { "x64" }
    Log "building NekoIMS ($arch)"
    $configure = ""
    if (-not (Test-Path (Join-Path $Build "CMakeCache.txt"))) {
        $configure = "cmake -S `"$Repo`" -B `"$Build`" -G Ninja -DCMAKE_BUILD_TYPE=Release && "
    }
    cmd /c "`"$vcvars`" $arch >nul && $configure cmake --build `"$Build`""
    if ($LASTEXITCODE) { Die "build failed" }
}

$Nekoims = Find-Nekoims
if (-not $Nekoims -or $Rebuild) {
    Invoke-Build
    $Nekoims = Find-Nekoims
}
if (-not $Nekoims) { Die "the build did not produce nekoims.exe" }

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Log "Administrator needed for the tunnel, re-running elevated"
    $argv = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-NoExit", "-File", "`"$PSCommandPath`"")
    foreach ($k in $PSBoundParameters.Keys) {
        $v = $PSBoundParameters[$k]
        if ($k -eq "Rebuild" -or $k -eq "NekoArgs") { continue }
        $argv += "-$k"
        $argv += "`"$v`""
    }
    if ($NekoArgs.Count) { $argv += "--"; $argv += $NekoArgs }
    Start-Process powershell -Verb RunAs -ArgumentList $argv
    exit 0
}

New-Item -ItemType Directory -Force $RunDir | Out-Null

# -- cleanup ---------------------------------------------------------------------

$script:SimProc = $null
$script:DialProc = $null
$script:NekoProc = $null
$FirewallRule = "NekoIMS (start.ps1)"

function Stop-All {
    if ($script:NekoProc -and -not $script:NekoProc.HasExited) {
        Stop-Process -Id $script:NekoProc.Id -Force -ErrorAction SilentlyContinue
    }
    if ($script:DialProc -and -not $script:DialProc.HasExited) {
        Log "hanging up the ePDG tunnel"
        # --lifeline: the dialer hangs up when its stdin closes
        try { $script:DialProc.StandardInput.Close() } catch {}
        if (-not $script:DialProc.WaitForExit(20000)) {
            Stop-Process -Id $script:DialProc.Id -Force -ErrorAction SilentlyContinue
        }
    }
    if ($script:SimProc -and -not $script:SimProc.HasExited) {
        Stop-Process -Id $script:SimProc.Id -Force -ErrorAction SilentlyContinue
    }
    Remove-NetFirewallRule -DisplayName $FirewallRule -ErrorAction SilentlyContinue
}

# Dialers a previous run left behind would fight over charon and Wintun
$leftover = Get-CimInstance Win32_Process -Filter "Name like 'python%' or Name = 'py.exe'" |
    Where-Object { $_.CommandLine -like "*strongswan-dialer.py*" }
if ($leftover) { Die "a dialer is already running (pid $($leftover.ProcessId -join ' ')), stop it first" }

try {

# -- 2. SIM server -----------------------------------------------------------------

function Test-Sim {
    try {
        $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 5 "$SimServer/?type=imsi"
        return $r.StatusCode -eq 200
    } catch { return $false }
}

$SimUp = Test-Sim
if ($Sim -eq "auto") { $Sim = if ($SimUp) { "server" } else { "pcsc" } }
Log "SIM backend: $Sim ($SimServer)"

if ($SimUp) {
    Log "using the SIM server on $SimServer"
} elseif ($Sim -eq "server") {
    Die "no SIM server answering on $SimServer"
} else {
    $u = [Uri]$SimServer
    if ($u.Host -ne "127.0.0.1" -and $u.Host -ne "localhost") {
        Die "no SIM server on $SimServer, and it is not local to start one"
    }
    $serverArgs = @("`"$Repo\simcard-server\server.py`"", "--listen", "127.0.0.1:$($u.Port)")
    if ($Reader -ge 0) { $serverArgs += @("--reader", $Reader) }
    $script:SimProc = Start-Process $Python -ArgumentList $serverArgs -NoNewWindow -PassThru `
        -RedirectStandardError (Join-Path $RunDir "simcard.log")
    for ($i = 0; $i -lt 50 -and -not (Test-Sim); $i++) {
        if ($script:SimProc.HasExited) {
            Get-Content (Join-Path $RunDir "simcard.log") -Tail 10 | Write-Host
            Die "SIM server exited"
        }
        Start-Sleep -Milliseconds 200
    }
    if (-not (Test-Sim)) { Die "SIM server did not come up on $SimServer" }
}

# -- 3. config ---------------------------------------------------------------------

$DialerHints = @()
if (-not $Config) {
    $Config = Join-Path $RunDir "config.json"
    $hints = Join-Path $RunDir "dialer.args"
    Log "generating $Config with mkconfig"
    $simSel = if ($Sim -eq "server") { @("--sim", "server") }
              else { @("--sim", "pcsc") + $(if ($Reader -ge 0) { @("--reader", $Reader) } else { @() }) }
    & $Python "$Repo\tools\mkconfig.py" @simSel --simcard-server $SimServer -o $Config --force --dialer-args $hints
    if ($LASTEXITCODE) { Die "mkconfig failed" }
    $DialerHints = @(Get-Content $hints | Where-Object { $_ })
}
if (-not (Test-Path $Config)) { Die "config $Config not found" }
if ((Get-Content $Config -Raw | ConvertFrom-Json).pcscf) {
    Log "note: $Config sets `"pcscf`", the one the ePDG assigns is used instead"
}

# -- 4. dial -----------------------------------------------------------------------

$DialLog = Join-Path $RunDir "dialer.log"
Remove-Item $PcscfFile, $DialLog -ErrorAction SilentlyContinue
$dialArgs = @("`"$Repo\dialers\strongswan-dialer.py`"", "--simcard", $SimServer,
              "--log", "`"$DialLog`"", "--lifeline") + $DialerHints
if ($Charon) { $dialArgs += @("--charon", "`"$Charon`"") }
else { $dialArgs += @("--remote", $(if ($Remote) { $Remote } else { $RemoteDefault })) }

Log "dialing the ePDG (log: $DialLog)"
$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $Python
$psi.Arguments = $dialArgs -join " "
$psi.UseShellExecute = $false
$psi.RedirectStandardInput = $true
$script:DialProc = [System.Diagnostics.Process]::Start($psi)

function Wait-Tunnel {
    for ($i = 0; $i -lt $DialTimeout * 5; $i++) {
        if ((Test-Path $PcscfFile) -and (Get-Item $PcscfFile).Length) { return $true }
        if ($script:DialProc.HasExited) { return $false }
        Start-Sleep -Milliseconds 200
    }
    return $false
}
if (-not (Wait-Tunnel)) {
    if (Test-Path $DialLog) { Get-Content $DialLog -Tail 25 | Write-Host }
    Die "no tunnel / P-CSCF from the ePDG"
}
Get-Content $DialLog | Where-Object { $_ -like "tunnel up*" } | Write-Host
Log "P-CSCF: $(Get-Content $PcscfFile -TotalCount 1)"

# Incoming calls and the external UA (B2BUA mode) reach NekoIMS unsolicited
New-NetFirewallRule -DisplayName $FirewallRule -Direction Inbound -Program $Nekoims `
    -Action Allow | Out-Null

# -- 5. NekoIMS --------------------------------------------------------------------

# NekoIMS registers over the tunnel it started on: when the dialer redials
# (new address, maybe a new P-CSCF; it rewrites the P-CSCF file, and removes
# it while down) NekoIMS is restarted once the new tunnel is up.
function Tunnel-Id {
    if (Test-Path $PcscfFile) { return (Get-Item $PcscfFile).LastWriteTimeUtc.Ticks }
    return "none"
}

while ($true) {
    if (-not (Wait-Tunnel)) { Die "the dialer exited or the tunnel did not come back" }
    $tunnel = Tunnel-Id
    Log "starting NekoIMS"
    # -p explicitly, not the P-CSCF file: older builds look in /run/nekoims
    $pcscf = (Get-Content $PcscfFile -TotalCount 1).Trim()
    $nekoArgv = @("-c", "`"$Config`"", "-p", $pcscf) + $NekoArgs
    $script:NekoProc = Start-Process $Nekoims -ArgumentList $nekoArgv -NoNewWindow -PassThru
    $null = $script:NekoProc.Handle  # else ExitCode stays empty after it exits
    $changed = $false
    while (-not $script:NekoProc.HasExited) {
        Start-Sleep -Seconds 2
        if ((Tunnel-Id) -ne $tunnel) { $changed = $true; break }
        if ($script:DialProc.HasExited) { break }
    }
    if (-not $changed) {
        $script:NekoProc.WaitForExit()
        exit $script:NekoProc.ExitCode
    }
    Log "the ePDG tunnel changed, restarting NekoIMS"
    Stop-Process -Id $script:NekoProc.Id -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

} finally {
    Stop-All
}
