#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
strongswan-dialer: bring up a VoWiFi (SWu) tunnel to the carrier's ePDG with a
private charon instance driven over vici, and expose it as a network interface
inside the `ims` netns.

Nothing is read from /etc/strongswan*: the dialer writes a throwaway
strongswan.conf under /run/nekoims, starts its own charon with
STRONGSWAN_CONF pointing at it, loads the connection over vici and removes
everything again on exit.

The tunnel is an XFRM interface (if_id), which is how stock strongSwan exposes
a route-based tunnel as a netdev; kernel-libipsec (a real TUN) isn't built
by most distros. The interface is moved into the netns, where the dialer
assigns the virtual IPs and default routes. charon itself stays in the init
netns, so the IKE/ESP traffic uses the normal uplink.

    sudo python3 simcard-server/server.py &
    sudo python3 dialers/strongswan-dialer.py [--epdg host] [--mnc-len 3]
    sudo ip netns exec ims ./build/nekoims

While the tunnel is up the P-CSCFs the ePDG assigned are in
/run/nekoims/pcscf (one per line), which nekoims reads when neither -p nor
"pcscf" in its config is given.

EAP-AKA needs RES/CK/IK from the USIM. Stock strongSwan has no client-side
backend that can reach a real card (eap-radius is EAP_SERVER only, the
3gpp2 card needs K), so this needs our strongSwan fork (branch `nekoims`):
its eap-aka-http plugin asks simcard-server, and it also carries the
Osmocom eap-sim-pcsc AKA patches (see AKA_BACKENDS). The fork's p-cscf
plugin is used when present to learn the P-CSCF from the ePDG.

Requires root, iproute2, a charon binary and the strongSwan python `vici`
package.

On Windows there are no network namespaces or XFRM interfaces. charon-svc
(the fork's Windows build, see --remote) runs kernel-libipsec: ESP is done in
userspace and the tunnel is a Wintun adapter (--ifname, "NekoIMS"), which
gets the virtual IPs, a host route to each P-CSCF and a default route with a
high metric. Windows' strong host model sends whatever is bound to the
tunnel address out of the tunnel, and the rest of the host keeps its own
routes. IKE runs from random local ports since Windows' IKEEXT service holds
500/4500, and ESP is always UDP-encapsulated. vici and the SIM server are on
loopback TCP (127.0.0.1:4502 and :8888). Run it as Administrator:

    python simcard-server/server.py
    python dialers/strongswan-dialer.py --remote <windows zip URL>
    build/nekoims.exe     (reads the P-CSCF from %ProgramData%\\NekoIMS)
"""
from __future__ import annotations

import argparse
import atexit
import base64
import glob
import hashlib
import http.client
import json
import os
import platform
import re
import shutil
import signal
import socket
import subprocess
import sys
import tarfile
import tempfile
import threading
import time
import urllib.error
import urllib.request
import zipfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLES_DEFAULT = os.path.join(REPO, "carrier-bundles")
WINDOWS = sys.platform == "win32"
if WINDOWS:
    RUN_DIR = os.path.join(os.environ.get("ProgramData", r"C:\ProgramData"),
                           "NekoIMS")
    # Python has no AF_UNIX on Windows, see simcard-server/server.py
    SIMCARD_DEFAULT = "http://127.0.0.1:8888"
    VICI_PORT = 4502  # charon-svc's default vici port
else:
    RUN_DIR = "/run/nekoims"
    SIMCARD_DEFAULT = "unix:/run/nekoims/simcard.sock"

CHARON_CANDIDATES = () if WINDOWS else (
    "/usr/local/libexec/ipsec/charon",  # fork, default prefix
    "/usr/lib/strongswan/charon",       # Arch
    "/usr/lib/ipsec/charon",            # Debian/Ubuntu
    "/usr/libexec/strongswan/charon",   # Fedora
    "/usr/libexec/ipsec/charon")
# Windows: the system's trusted roots, see load_cas()
CA_BUNDLE_DEFAULT = None if WINDOWS else "/etc/ssl/certs/ca-certificates.crt"

CONN = "epdg"
CHILD = "ims"
IF_ID = 0x4e4b  # "NK"

# MCCs in the North American Numbering Plan use 3-digit MNCs.
NANP_MCCS = {"302"} | {str(m) for m in range(310, 317)}

# Typical ePDG offers (TS 33.210 / GSMA IR.51 profiles); bundles can override
# with "ike_proposals" / "esp_proposals".
IKE_PROPOSALS = ["aes256-sha256-modp2048", "aes128-sha256-modp2048",
                 "aes128-sha1-modp2048", "aes128-sha1-modp1024"]
ESP_PROPOSALS = ["aes128-sha1", "aes256-sha256", "aes128gcm16", "aes256gcm16"]

# charon plugins needed for an IKEv2 EAP-AKA initiator, without stroke,
# resolve (it would rewrite /etc/resolv.conf) or anything else from
# /etc/strongswan.d. The AKA backend adds its own. Crypto comes from openssl
# on distro builds, or the built-in plugins (aes ... curve25519) on a static
# monolithic build without OpenSSL; charon just warns about missing ones.
BASE_PLUGINS = ["random", "nonce", "openssl",
                "drbg", "aes", "sha1", "sha2", "gmp", "curve25519",
                "x509", "pem", "pubkey",
                "pkcs1", "pkcs8", "constraints", "hmac", "kdf",
                "fips-prf",  # EAP-AKA's PRF_FIPS_SHA1_160
                "kernel-netlink", "socket-default", "vici",
                "eap-identity", "eap-aka"]
if WINDOWS:
    # IP Helper for addresses and routes, Winsock for IKE, userspace ESP on
    # a Wintun adapter. No openssl: the build has the built-in crypto only.
    BASE_PLUGINS = [p for p in BASE_PLUGINS
                    if p not in ("openssl", "kernel-netlink", "socket-default")]
    BASE_PLUGINS += ["kernel-iph", "socket-win", "kernel-libipsec"]


def log(msg: str):
    print(msg, file=sys.stderr, flush=True)


def s(v) -> str:
    """vici returns bytes for every value."""
    return v.decode() if isinstance(v, bytes) else str(v)


# -- simcard-server ----------------------------------------------------------

class UnixHTTPConnection(http.client.HTTPConnection):
    def __init__(self, path: str, timeout: float = 5.0):
        super().__init__("simcard", timeout=timeout)
        self.unix_path = path

    def connect(self):
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.sock.settimeout(self.timeout)
        self.sock.connect(self.unix_path)


class SimClient:
    """Client for simcard-server/server.py (USIM-https-server API).
    where: "unix:/path" (or a bare path) or "http://host:port"."""

    def __init__(self, where: str):
        if re.match(r"https?://", where):
            self.where = where.rstrip("/")
        else:
            self.where = "unix:" + where.removeprefix("unix:")

    def _get(self, query: str) -> dict:
        if self.where.startswith("unix:"):
            conn = UnixHTTPConnection(self.where[len("unix:"):])
        else:
            conn = http.client.HTTPConnection(
                re.sub(r"^https?://", "", self.where), timeout=5.0)
        try:
            conn.request("GET", "/?" + query)
            resp = conn.getresponse()
            body = json.loads(resp.read() or b"{}")
        finally:
            conn.close()
        if resp.status != 200:
            raise RuntimeError(f"simcard-server: HTTP {resp.status}: "
                               f"{body.get('error', '?')}")
        return body

    def imsi(self) -> str:
        return self._get("type=imsi")["imsi"]



# -- AKA backends ------------------------------------------------------------

class AkaBackend:
    """Feeds charon's eap-aka peer with RES/CK/IK. Subclasses add plugins and
    strongswan.conf settings and may run a helper next to charon."""

    plugins: list[str] = []

    def __init__(self, sim: SimClient):
        self.sim = sim

    def settings(self) -> str:
        return ""

    def start(self):
        pass

    def stop(self):
        pass


class NoAkaBackend(AkaBackend):
    """No card: IKE_SA_INIT, certificates and IDr can be tested, EAP fails."""

    def start(self):
        log("warning: --aka-backend none, EAP-AKA will fail with "
            "'no AKA card found'")


class HttpAkaBackend(AkaBackend):
    """eap-aka-http from our strongSwan fork: charon asks simcard-server
    for RES/CK/IK (and AUTS on a sync failure) itself."""

    plugins = ["eap-aka-http"]

    def settings(self) -> str:
        return (f"eap-aka-http {{\n"
                f"      server = {self.sim.where}\n"
                f"    }}\n")


class PcscAkaBackend(AkaBackend):
    """eap-sim-pcsc with the Osmocom AKA patches (also in our fork).
    charon then talks to pcscd directly; simcard-server keeps working
    alongside since PC/SC connections are shared."""

    plugins = ["eap-sim-pcsc"]


AKA_BACKENDS = {"http": HttpAkaBackend, "pcsc": PcscAkaBackend,
                "none": NoAkaBackend}


# -- carrier -----------------------------------------------------------------

def find_bundle(imsi: str, bundles_dir: str) -> dict:
    """The bundle whose digit name is the longest prefix of the IMSI."""
    best, best_len = None, -1
    for path in glob.glob(os.path.join(bundles_dir, "*.json")):
        digits = re.sub(r"\D", "", os.path.splitext(os.path.basename(path))[0])
        if digits and imsi.startswith(digits) and len(digits) > best_len:
            best, best_len = path, len(digits)
    if not best:
        return {}
    with open(best) as f:
        return json.load(f)


def nai(imsi: str, mcc: str, mnc: str) -> str:
    """Root NAI for EAP-AKA over SWu (TS 23.003 19.3.2)."""
    return f"0{imsi}@nai.epc.mnc{mnc.zfill(3)}.mcc{mcc}.3gppnetwork.org"


# -- netns / XFRM interface --------------------------------------------------

def ip(*args, check=True):
    return subprocess.run(["ip", *args], check=check,
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                          text=True)


class Tunnel:
    """XFRM interface carrying if_id IF_ID, living in `netns`.

    With an empty netns the interface stays in the current namespace (e.g. a
    container that also has to reach a LAN): traffic from the tunnel address
    goes through it via a policy rule, and it becomes the IPv6 default route
    only if there is no other one, so the LAN side and IKE keep their routes.
    """

    def __init__(self, netns: str, ifname: str, mtu: int):
        self.netns, self.ifname, self.mtu = netns, ifname, mtu
        self.vips: list[str] = []
        self.main_v6_default = False

    def _ip(self, *args, check=True):
        ns = ("-n", self.netns) if self.netns else ()
        return ip(*ns, *args, check=check)

    def create(self):
        if self.netns and self.netns not in ip("netns", "list").stdout.split():
            ip("netns", "add", self.netns)
        self._ip("link", "del", self.ifname, check=False)
        ip("link", "add", self.ifname, "type", "xfrm", "if_id", hex(IF_ID))
        if self.netns:
            ip("link", "set", self.ifname, "netns", self.netns)
            self._ip("link", "set", "lo", "up")
        self._ip("link", "set", self.ifname, "mtu", str(self.mtu), "up")

    def configure(self, vips: list[str]):
        self.unconfigure()
        for vip in vips:
            v6 = ":" in vip
            fam = "-6" if v6 else "-4"
            self._ip("addr", "add", f"{vip}/{128 if v6 else 32}",
                     "dev", self.ifname)
            if self.netns:
                self._ip(fam, "route", "replace", "default", "dev",
                         self.ifname)
                continue
            ip(fam, "rule", "add", "from", vip, "lookup", str(IF_ID),
               "priority", str(IF_ID))
            ip(fam, "route", "replace", "default", "dev", self.ifname,
               "table", str(IF_ID))
            if v6 and not ip("-6", "route", "show", "default").stdout.strip():
                ip("-6", "route", "add", "default", "dev", self.ifname)
                self.main_v6_default = True
        self.vips = vips

    def unconfigure(self):
        self._ip("addr", "flush", "dev", self.ifname, check=False)
        if self.netns:
            return
        for vip in self.vips:
            fam = "-6" if ":" in vip else "-4"
            ip(fam, "rule", "del", "from", vip, "lookup", str(IF_ID),
               check=False)
            ip(fam, "route", "flush", "table", str(IF_ID), check=False)
        if self.main_v6_default:
            ip("-6", "route", "del", "default", "dev", self.ifname,
               check=False)
            self.main_v6_default = False
        self.vips = []

    def destroy(self):
        self.unconfigure()
        self._ip("link", "del", self.ifname, check=False)


def netsh(*args, check=True) -> subprocess.CompletedProcess:
    r = subprocess.run(["netsh", *args], stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT, text=True)
    if check and r.returncode:
        raise RuntimeError(f"netsh {' '.join(args)}: {r.stdout.strip()}")
    return r


def powershell(command: str, check=True) -> subprocess.CompletedProcess:
    r = subprocess.run(["powershell", "-NoProfile", "-NonInteractive",
                        "-Command", command], stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT, text=True)
    if check and r.returncode:
        raise RuntimeError(f"powershell {command}: {r.stdout.strip()}")
    return r


class WintunTunnel:
    """The Wintun adapter charon's kernel-libipsec creates on Windows
    (kernel-libipsec.tun_name) and removes again when it exits.

    There are no network namespaces. The adapter gets the virtual IPs, a
    host route to each P-CSCF and a default route with a high metric, so the
    host's own routes stay preferred. Windows' strong host model keeps
    traffic bound to the tunnel address (NekoIMS' SIP and RTP) on the
    adapter's routes, i.e. in the tunnel. Inbound traffic on the adapter is
    let through the firewall, which treats it as an unidentified (public)
    network and would drop incoming calls.
    """

    METRIC = 9000
    FIREWALL_RULE = "NekoIMS ePDG tunnel"

    def __init__(self, ifname: str, mtu: int):
        self.ifname, self.mtu = ifname, mtu
        self.netns = ""
        self.vips: list[str] = []
        self.routes: list[tuple[str, str]] = []  # (ipv4|ipv6, prefix)
        self.firewall = False

    def create(self):
        """Nothing to do before charon runs, it creates the adapter."""

    def setup(self):
        """Once charon (and so the adapter) is up: MTU, metric, no DAD or
        router discovery, firewall."""
        name = f"interface={self.ifname}"
        # IPv4 may be unbound from the adapter (see configure()), and the
        # adapter keeps its GUID and settings from run to run
        netsh("interface", "ipv4", "set", "subinterface", self.ifname,
              f"mtu={self.mtu}", "store=active", check=False)
        netsh("interface", "ipv4", "set", "interface", name,
              f"metric={self.METRIC}", "store=active", check=False)
        if self.mtu >= 1280:
            netsh("interface", "ipv6", "set", "subinterface", self.ifname,
                  f"mtu={self.mtu}", "store=active")
        netsh("interface", "ipv6", "set", "interface", name,
              f"metric={self.METRIC}", "dadtransmits=0",
              "routerdiscovery=disabled", "store=active")
        powershell(f"Remove-NetFirewallRule -DisplayName "
                   f"'{self.FIREWALL_RULE}' -ErrorAction SilentlyContinue",
                   check=False)
        powershell(f"New-NetFirewallRule -DisplayName '{self.FIREWALL_RULE}' "
                   f"-Direction Inbound -InterfaceAlias '{self.ifname}' "
                   f"-Action Allow | Out-Null")
        self.firewall = True

    def _route(self, fam: str, prefix: str, metric: int):
        netsh("interface", fam, "add", "route", f"prefix={prefix}",
              f"interface={self.ifname}", f"metric={metric}", "store=active")
        self.routes.append((fam, prefix))

    def configure(self, vips: list[str], pcscfs: list[str] = ()):
        self.unconfigure()
        # Without an IPv4 address from the ePDG (Verizon is IPv6-only),
        # Windows gives the adapter a 169.254/16 one that can't be bound
        # (WSAEADDRNOTAVAIL), so leave IPv4 off it entirely.
        v4 = any(":" not in v for v in vips)
        powershell(f"{'Enable' if v4 else 'Disable'}-NetAdapterBinding "
                   f"-Name '{self.ifname}' -ComponentID ms_tcpip", check=False)
        for vip in vips:
            if ":" in vip:
                netsh("interface", "ipv6", "add", "address",
                      f"interface={self.ifname}", f"address={vip}/128",
                      "store=active")
                self._route("ipv6", "::/0", self.METRIC)
            else:
                netsh("interface", "ipv4", "add", "address",
                      f"name={self.ifname}", f"address={vip}",
                      "mask=255.255.255.255", "store=active")
                self._route("ipv4", "0.0.0.0/0", self.METRIC)
        self.vips = vips
        fams = {":" in v for v in vips}
        for p in pcscfs:
            v6 = ":" in p
            if v6 in fams:
                self._route("ipv6" if v6 else "ipv4",
                            f"{p}/{128 if v6 else 32}", 1)

    def unconfigure(self):
        for fam, prefix in self.routes:
            netsh("interface", fam, "delete", "route", f"prefix={prefix}",
                  f"interface={self.ifname}", "store=active", check=False)
        self.routes = []
        for vip in self.vips:
            if ":" in vip:
                netsh("interface", "ipv6", "delete", "address",
                      f"interface={self.ifname}", f"address={vip}",
                      "store=active", check=False)
            else:
                netsh("interface", "ipv4", "delete", "address",
                      f"name={self.ifname}", f"address={vip}",
                      "store=active", check=False)
        self.vips = []

    def destroy(self):
        self.unconfigure()
        if self.firewall:
            powershell(f"Remove-NetFirewallRule -DisplayName "
                       f"'{self.FIREWALL_RULE}'", check=False)
            self.firewall = False


# -- charon ------------------------------------------------------------------

def find_charon(override: str | None) -> str:
    for path in ([override] if override else CHARON_CANDIDATES):
        if path and os.access(path, os.X_OK):
            return path
    sys.exit("charon not found, pass --charon")


def find_plugin_dir(charon_bin: str, override: str | None) -> str | None:
    """Distro packages keep plugins next to charon; autotools installs put
    charon in <prefix>/libexec/ipsec and plugins in <prefix>/lib/ipsec.
    None for a monolithic charon, which has its plugins built in."""
    if override:
        return override
    here = os.path.dirname(charon_bin)
    prefix = os.path.dirname(os.path.dirname(here))
    for d in (os.path.join(here, "plugins"),
              os.path.join(prefix, "lib", "ipsec", "plugins")):
        if os.path.isdir(d):
            return d
    return None


def vici_uri(vici_socket: str) -> str:
    if WINDOWS:
        return f"tcp://127.0.0.1:{VICI_PORT}"
    return f"unix://{vici_socket}"


def strongswan_conf(vici_socket: str, plugins: list[str], aka: AkaBackend,
                    loglevel: int, ifname: str) -> str:
    # Windows: IKEEXT holds 500/4500, so IKE uses random local ports (the
    # ePDG's stay 500/4500); kernel-libipsec names its Wintun adapter.
    windows = f"""\
  port = 0
  port_nat_t = 0
""" if WINDOWS else ""
    libipsec = f"""\
    kernel-libipsec {{
      tun_name = {ifname}
    }}
""" if WINDOWS else ""
    return f"""\
charon {{
  load_modular = no
  load = {" ".join(plugins)}
  # Addresses and routes go on the tunnel interface instead (the XFRM
  # interface in the netns, or the Wintun adapter on Windows).
  install_virtual_ip = no
  install_routes = no
{windows}  plugins {{
    vici {{
      socket = {vici_uri(vici_socket)}
    }}
{libipsec}    p-cscf {{
      enable {{
        {CONN} = yes
      }}
    }}
    {aka.settings()}  }}
  filelog {{
    stderr {{
      default = {loglevel}
      ike_name = yes
    }}
  }}
}}
"""


class Charon:
    def __init__(self, binary: str, conf: str, vici_socket: str, log=None):
        self.binary, self.conf, self.vici_socket = binary, conf, vici_socket
        self.log = log  # file for charon's output, else ours
        self.proc = None

    def _connect(self) -> socket.socket:
        if WINDOWS:
            return socket.create_connection(("127.0.0.1", VICI_PORT), 2)
        sock = socket.socket(socket.AF_UNIX)
        sock.connect(self.vici_socket)
        return sock

    def _vici_up(self) -> bool:
        try:
            self._connect().close()
            return True
        except OSError:
            return False

    def start(self):
        if WINDOWS:
            self._start_windows()
            return
        pid = "/run/charon.pid"
        if os.path.exists(pid):
            try:
                with open(pid) as f:
                    os.kill(int(f.read().strip()), 0)
                sys.exit("another charon is running (strongswan.service?); "
                         "stop it first, charon allows one instance")
            except (ValueError, ProcessLookupError):
                pass
        if os.path.exists(self.vici_socket):
            os.unlink(self.vici_socket)
        env = dict(os.environ, STRONGSWAN_CONF=self.conf)
        self.proc = subprocess.Popen([self.binary], env=env, stdout=self.log,
                                     stderr=self.log)
        deadline = time.monotonic() + 10
        while not os.path.exists(self.vici_socket):
            if self.proc.poll() is not None:
                sys.exit(f"charon exited with {self.proc.returncode}")
            if time.monotonic() > deadline:
                sys.exit("charon did not open its vici socket")
            time.sleep(0.1)

    def _start_windows(self):
        """charon-svc runs in the console when not started as a service. Its
        own process group, so Ctrl-C reaches only us and we stop it with
        CTRL_BREAK (a clean exit that removes the Wintun adapter)."""
        if self._vici_up():
            sys.exit(f"another charon answers on vici port {VICI_PORT} (the "
                     f"strongSwan service, or a dialer left running?); stop "
                     f"it first")
        env = dict(os.environ, STRONGSWAN_CONF=self.conf)
        self.proc = subprocess.Popen(
            [self.binary], env=env, stdout=self.log, stderr=self.log,
            stdin=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
        deadline = time.monotonic() + 15
        while not self._vici_up():
            if self.proc.poll() is not None:
                sys.exit(f"charon exited with {self.proc.returncode} (as "
                         f"Administrator? wintun.dll next to it?)")
            if time.monotonic() > deadline:
                sys.exit("charon did not open its vici port")
            time.sleep(0.2)

    def check(self):
        """Exit if charon died; there is nothing left to redial with."""
        rc = None
        if self.proc:
            try:  # a lost vici connection can come before charon is gone
                rc = self.proc.wait(2)
            except subprocess.TimeoutExpired:
                pass
        if rc is None:
            return
        if WINDOWS and rc >= 0xC0000000:  # NTSTATUS, e.g. an access violation
            why = f"crashed with 0x{rc:08X}"
        elif rc < 0:
            try:
                why = f"killed by {signal.Signals(-rc).name}"
            except ValueError:
                why = f"killed by signal {-rc}"
        else:
            why = f"exited with {rc}"
        sys.exit(f"charon {why}")

    def session(self):
        import vici
        sock = self._connect()
        sock.settimeout(None)
        return vici.Session(sock)

    def stop(self):
        if self.proc and self.proc.poll() is None:
            if WINDOWS:
                self.proc.send_signal(signal.CTRL_BREAK_EVENT)
            else:
                self.proc.terminate()
            try:
                self.proc.wait(10)
            except subprocess.TimeoutExpired:
                self.proc.kill()


# -- --remote: a static build from a tarball ---------------------------------

def remote_arch() -> str:
    """Architecture name used by the release tarballs."""
    m = platform.machine()
    if WINDOWS:
        # The OS's, not this Python's: x64 Python runs emulated on ARM64
        import ctypes
        proc, native = ctypes.c_ushort(), ctypes.c_ushort()
        k32 = ctypes.windll.kernel32
        if k32.IsWow64Process2(k32.GetCurrentProcess(), ctypes.byref(proc),
                               ctypes.byref(native)):
            m = {0xAA64: "arm64", 0x8664: "x86_64"}.get(native.value, m)
        # There is no native arm64 build: clang miscompiles struct varargs
        # (chunk_t) on Windows arm64, see neko-strongswan's
        # build-windows.sh. The x86_64 one runs emulated, Wintun included.
        if m == "arm64":
            m = "x86_64"
    return {"aarch64": "arm64", "amd64": "x86_64",
            "AMD64": "x86_64", "ARM64": "arm64"}.get(m, m)


def fetch(url: str, dest: str) -> str:
    """Download url (or copy a local path) to dest, returns its sha256."""
    h = hashlib.sha256()
    if re.match(r"https?://", url):
        req = urllib.request.Request(url, headers={"User-Agent": "nekoims"})
        src = urllib.request.urlopen(req, timeout=60)
    else:
        src = open(url, "rb")
    with src, open(dest, "wb") as f:
        while chunk := src.read(1 << 16):
            h.update(chunk)
            f.write(chunk)
    return h.hexdigest()


def published_sha256(url: str) -> str | None:
    """The <url>.sha256 sidecar the release workflow uploads, if any."""
    if not re.match(r"https?://", url):
        path = url + ".sha256"
        if not os.path.exists(path):
            return None
        with open(path) as f:
            return f.read().split()[0].lower()
    req = urllib.request.Request(url + ".sha256",
                                 headers={"User-Agent": "nekoims"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read().decode().split()[0].lower()
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def extract(archive: str, dest: str):
    if zipfile.is_zipfile(archive):
        with zipfile.ZipFile(archive) as z:
            root = os.path.realpath(dest)
            for name in z.namelist():
                target = os.path.realpath(os.path.join(dest, name))
                if os.path.commonpath([root, target]) != root:
                    sys.exit(f"--remote: refusing archive member {name!r}")
            z.extractall(dest)
        return
    with tarfile.open(archive, "r:gz") as tar:
        if hasattr(tarfile, "data_filter"):
            tar.extractall(dest, filter="data")
            return
        root = os.path.realpath(dest)
        for m in tar.getmembers():
            target = os.path.realpath(os.path.join(dest, m.name))
            if (os.path.commonpath([root, target]) != root or
                    m.issym() or m.islnk() or m.isdev()):
                sys.exit(f"--remote: refusing archive member {m.name!r}")
        tar.extractall(dest)


def use_remote(url: str, pinned: str | None) -> str:
    """Download and unpack a static strongSwan build (see the neko-strongswan
    release workflow) into a private directory that is removed on exit.
    Returns the charon path; its vici Python client is put on sys.path."""
    url = url.replace("{arch}", remote_arch())
    work = tempfile.mkdtemp(prefix="strongswan-", dir=RUN_DIR)
    atexit.register(shutil.rmtree, work, ignore_errors=True)

    archive = os.path.join(work, "strongswan.zip" if WINDOWS
                           else "strongswan.tar.gz")
    log(f"fetching {url}")
    try:
        digest = fetch(url, archive)
        expected = pinned or published_sha256(url)
    except (OSError, urllib.error.URLError) as e:
        sys.exit(f"--remote: {e}")
    if expected:
        if digest != expected.lower():
            sys.exit(f"--remote: sha256 mismatch, got {digest}, "
                     f"expected {expected}")
        log(f"sha256 {digest} verified")
    else:
        log(f"warning: no sha256 to verify {url} against (got {digest}), "
            f"pin it with --remote-sha256")

    root = os.path.join(work, "root")
    try:
        extract(archive, root)
    except (tarfile.TarError, OSError) as e:
        sys.exit(f"--remote: bad archive: {e}")
    os.unlink(archive)
    binary = "bin/charon-svc.exe" if WINDOWS else "libexec/ipsec/charon"
    found = glob.glob(os.path.join(root, binary)) + \
        glob.glob(os.path.join(root, "*", binary))
    if len(found) != 1:
        sys.exit(f"--remote: archive has no (unique) {binary}")
    charon = found[0]
    pkg = os.path.dirname(os.path.dirname(charon))
    if not WINDOWS:
        pkg = os.path.dirname(pkg)
    python = os.path.join(pkg, "lib", "python")
    if os.path.isdir(os.path.join(python, "vici")):
        sys.path.insert(0, python)
    return charon


# -- vici --------------------------------------------------------------------

def load_cas(session, paths: list[str] | None) -> int:
    """Trust anchors for the ePDG certificate, loaded over vici: the PEM
    bundles in paths, or the system's trusted roots (Windows). Ones charon
    can't parse (e.g. ECDSA roots on a build without an EC plugin) are
    skipped rather than failing the whole dial."""
    from vici.exception import CommandException
    ders = []
    if paths is None:
        import ssl
        ders = ssl.create_default_context().get_ca_certs(binary_form=True)
    for path in paths or []:
        with open(path) as f:
            pem = f.read()
        ders += [base64.b64decode(b64) for b64 in
                 re.findall(r"-----BEGIN CERTIFICATE-----(.*?)"
                            r"-----END CERTIFICATE-----", pem, re.S)]
    n = skipped = 0
    for der in ders:
        try:
            session.load_cert({"type": "x509", "flag": "CA", "data": der})
            n += 1
        except CommandException:
            skipped += 1
    if skipped:
        log(f"skipped {skipped} CA certificates charon could not parse")
    return n


def epdg_addrs(epdg: str, family: str) -> list[str]:
    """The ePDG host, or its addresses of one family (e.g. IPv4 only from a
    container whose IPv6 default route is the tunnel itself)."""
    if family == "any":
        return [epdg]
    af = socket.AF_INET if family == "4" else socket.AF_INET6
    try:
        infos = socket.getaddrinfo(epdg, 500, af, socket.SOCK_DGRAM)
    except socket.gaierror as e:
        sys.exit(f"cannot resolve {epdg} to IPv{family}: {e}")
    return list(dict.fromkeys(i[4][0] for i in infos))


def connection(epdg: str, identity: str, remote_id: str, remote_auth: str,
               bundle: dict, encap: bool = True,
               family: str = "any") -> dict:
    return {CONN: {
        "version": "2",
        # Always carry ESP in UDP 4500, like phones do. Without a NAT (e.g.
        # IPv6) charon would send raw ESP (IP protocol 50), which home
        # routers' firewalls commonly drop: IKE comes up but no data flows.
        "encap": "yes" if encap else "no",
        "remote_addrs": epdg_addrs(epdg, family),
        # Request INTERNAL_IP4/6_ADDRESS; with the p-cscf plugin loaded
        # charon also asks for P_CSCF_IP4/6_ADDRESS.
        "vips": ["0.0.0.0", "::"],
        "proposals": bundle.get("ike_proposals", IKE_PROPOSALS),
        "keyingtries": "1",
        "dpd_delay": "120s",
        "local": {"auth": "eap-aka", "id": identity},
        # IDr carries the APN (TS 24.302 7.2.2), but the ePDG identifies as
        # one of its nodes, so don't require a match (id_check is from our
        # fork). The ePDG is authenticated by its certificate, or with "eap"
        # (RFC 5998 EAP-only, e.g. Verizon) by the EAP-AKA MSK.
        "remote": {"auth": "eap-aka" if remote_auth == "eap" else "pubkey",
                   "id": remote_id, "id_check": "no"},
        "children": {CHILD: {
            "remote_ts": ["0.0.0.0/0", "::/0"],
            "esp_proposals": bundle.get("esp_proposals", ESP_PROPOSALS),
            # the XFRM interface's; kernel-libipsec (Windows) ignores it
            "if_id_in": hex(IF_ID),
            "if_id_out": hex(IF_ID),
            "start_action": "none",
            "dpd_action": "clear",
            "close_action": "none",
        }},
    }}


P_CSCF_RE = re.compile(r"received P-CSCF server IP (\S+)")
# The ePDG authenticated itself with the EAP MSK (RFC 5998) while we wanted
# a certificate.
EAP_ONLY_RE = re.compile(r"constraint requires public key authentication, "
                         r"but EAP was used")


def initiate(session, logs: list[str] | None = None) -> list[str]:
    """Bring the tunnel up; returns the P-CSCFs charon logged on the way.
    The log lines go to logs too, for a look after a failure."""
    pcscfs = []
    for msg in session.initiate({"child": CHILD, "ike": CONN,
                                 "timeout": "30000", "loglevel": "1"}):
        line = s(msg.get("msg", b""))
        if logs is not None:
            logs.append(line)
        m = P_CSCF_RE.search(line)
        if m and m.group(1) not in pcscfs:
            pcscfs.append(m.group(1))
    return pcscfs


def local_vips(session) -> list[str]:
    for sa in session.list_sas({"ike": CONN}):
        if CONN in sa:
            return [s(v) for v in sa[CONN].get("local-vips", [])]
    return []


def wait_down(events):
    """Block until our IKE SA goes away. On Windows in a thread: Ctrl-C
    (and --lifeline) can't interrupt a blocking recv() there."""
    def listen():
        for kind, msg in events.listen(["ike-updown"]):
            if CONN in msg and s(msg.get("up", b"no")) != "yes":
                return

    if not WINDOWS:
        listen()
        return
    done, err = threading.Event(), []

    def run():
        try:
            listen()
        except Exception as e:  # vici connection lost
            err.append(e)
        finally:
            done.set()
    threading.Thread(target=run, daemon=True).start()
    while not done.wait(0.5):
        pass
    if err:
        raise err[0]


def is_admin() -> bool:
    if WINDOWS:
        import ctypes
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    return os.geteuid() == 0


def write_state(path: str, state: dict | None):
    if state is None:
        if os.path.exists(path):
            os.unlink(path)
        return
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(state, f, indent=2)
    os.replace(tmp, path)


def tunnel_family_first(pcscfs: list[str], vips: list[str]) -> list[str]:
    """P-CSCFs in an address family the tunnel has go first (stable order
    otherwise). Some ePDGs hand out IPv4 and IPv6 P-CSCFs on a tunnel that
    only has one family (Freedom: IPv6-only, IPv4 ones listed first), and
    nekoims takes the first line of the pcscf file. Bundle flag
    "pcscf_match_family"."""
    fams = {":" in v for v in vips}
    ordered = sorted(pcscfs, key=lambda p: (":" in p) not in fams)
    if ordered and (":" in ordered[0]) not in fams:
        log(f"warning: no P-CSCF matches the tunnel's address family "
            f"({' '.join(vips)}): {' '.join(pcscfs)}")
    return ordered


def write_pcscf(path: str, pcscfs: list[str] | None):
    """One P-CSCF per line, read by nekoims when no -p/"pcscf" is given.
    Removed while there is no tunnel (or no P-CSCF) so it is never stale."""
    if not pcscfs:
        if os.path.exists(path):
            os.unlink(path)
        return
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write("".join(p + "\n" for p in pcscfs))
    os.replace(tmp, path)


# -- main --------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--simcard", default=SIMCARD_DEFAULT,
                    help="simcard-server: unix:/path (or a bare path) or "
                         f"http://host:port (default: {SIMCARD_DEFAULT})")
    ap.add_argument("--bundles", default=BUNDLES_DEFAULT)
    ap.add_argument("--epdg", default=None, help="ePDG host (default: "
                    "carrier bundle, else 3GPP discovery name)")
    ap.add_argument("--mnc-len", type=int, choices=(2, 3), default=None,
                    help="MNC digits in the IMSI (default: 3 for NANP, else 2)")
    ap.add_argument("--apn", default=None, help="APN (default: bundle or ims)")
    ap.add_argument("--remote-id", default=None,
                    help="IDr to send (default: the APN)")
    ap.add_argument("--no-encap", action="store_true",
                    help="send raw ESP when there is no NAT instead of "
                         "always encapsulating it in UDP 4500 (not on "
                         "Windows)")
    ap.add_argument("--remote-auth", choices=("pubkey", "eap"), default=None,
                    help="how the ePDG authenticates (default: bundle "
                         "epdg_auth, else pubkey with a fallback to eap if "
                         "the ePDG turns out to be EAP-only)")
    ap.add_argument("--ca", action="append", default=None,
                    help=f"CA bundle(s) for the ePDG certificate "
                         f"(default: {CA_BUNDLE_DEFAULT or 'the system store'})")
    ap.add_argument("--aka-backend", choices=sorted(AKA_BACKENDS),
                    default="http")
    ap.add_argument("--netns", default="" if WINDOWS else "ims",
                    help='netns for the tunnel interface, "" to keep it in '
                         "the current one (e.g. in a container); Linux only")
    ap.add_argument("--epdg-family", choices=("any", "4", "6"),
                    default="any",
                    help="reach the ePDG over this IP version only")
    ap.add_argument("--ifname", default="NekoIMS" if WINDOWS else "ims0",
                    help="tunnel interface (Windows: the Wintun adapter)")
    ap.add_argument("--mtu", type=int, default=1400)
    ap.add_argument("--charon", default=None, help="charon binary")
    ap.add_argument("--remote", default=None, metavar="URL",
                    help="run the static strongSwan build from this tar.gz "
                         "(.zip on Windows; URL or path, {arch} expands to "
                         "x86_64/arm64) instead of an installed charon")
    ap.add_argument("--remote-sha256", default=None, metavar="HEX",
                    help="expected sha256 of the --remote tarball (default: "
                         "the published <URL>.sha256, if any)")
    ap.add_argument("--plugin-dir", default=None,
                    help="charon plugin directory (default: guessed)")
    ap.add_argument("--loglevel", type=int, default=1,
                    help="charon log level (-1..4)")
    ap.add_argument("--retry", type=int, default=10,
                    help="seconds between redials, 0 to exit on failure")
    ap.add_argument("--log", default=None, metavar="PATH",
                    help="append our and charon's output here")
    ap.add_argument("--lifeline", action="store_true",
                    help="hang up and exit when stdin closes (for a parent "
                         "process that can't signal us, e.g. start.ps1)")
    args = ap.parse_args()

    log_file = None
    if args.log:
        log_file = open(args.log, "a", buffering=1)
        sys.stdout = sys.stderr = log_file
    if args.lifeline:
        import _thread

        def lifeline():
            # EOF once the parent is gone. os.read, not the buffered
            # sys.stdin, whose lock would hang interpreter shutdown.
            while os.read(sys.stdin.fileno(), 4096):
                pass
            log("stdin closed, hanging up")
            _thread.interrupt_main()
        threading.Thread(target=lifeline, daemon=True).start()

    if not is_admin():
        sys.exit("must run as Administrator" if WINDOWS else
                 "must run as root")
    if WINDOWS and args.netns:
        sys.exit("--netns: there are no network namespaces on Windows")
    if WINDOWS and args.no_encap:
        sys.exit("--no-encap: kernel-libipsec on Windows has no raw ESP")
    if args.remote and args.charon:
        sys.exit("--remote and --charon are mutually exclusive")
    if args.remote:
        os.makedirs(RUN_DIR, mode=0o750, exist_ok=True)
        args.charon = use_remote(args.remote, args.remote_sha256)
    elif args.charon:
        # An unpacked release (bin/charon-svc.exe, libexec/ipsec/charon)
        # brings its vici client in lib/python
        d = os.path.dirname(os.path.abspath(args.charon))
        for _ in range(3):
            d = os.path.dirname(d)
            if os.path.isdir(os.path.join(d, "lib", "python", "vici")):
                sys.path.insert(0, os.path.join(d, "lib", "python"))
                break
    try:
        import vici  # noqa: F401
    except ImportError:
        sys.exit("python vici module missing (strongSwan's "
                 "src/libcharon/plugins/vici/python)")

    sim = SimClient(args.simcard)
    try:
        imsi = sim.imsi()
    except (OSError, RuntimeError, KeyError, ValueError) as e:
        sys.exit(f"cannot get the IMSI from the SIM server on {args.simcard}: "
                 f"{e}")
    mcc = imsi[:3]
    mnc_len = args.mnc_len or (3 if mcc in NANP_MCCS else 2)
    mnc = imsi[3:3 + mnc_len]
    bundle = find_bundle(imsi, args.bundles)
    epdg = args.epdg or bundle.get("epdg") or \
        f"epdg.epc.mnc{mnc.zfill(3)}.mcc{mcc}.pub.3gppnetwork.org"
    apn = args.apn or bundle.get("apn", "ims")
    identity = nai(imsi, mcc, mnc)
    log(f"IMSI {imsi}, identity {identity}, ePDG {epdg}, APN {apn}")

    os.makedirs(RUN_DIR, mode=0o750, exist_ok=True)
    conf = os.path.join(RUN_DIR, "strongswan.conf")
    vici_socket = os.path.join(RUN_DIR, "charon.vici")
    state_path = os.path.join(RUN_DIR, "epdg.json")
    pcscf_path = os.path.join(RUN_DIR, "pcscf")

    charon_bin = find_charon(args.charon)
    plugin_dir = find_plugin_dir(charon_bin, args.plugin_dir)
    aka = AKA_BACKENDS[args.aka_backend](sim)
    plugins = BASE_PLUGINS + aka.plugins
    if not plugin_dir:
        log("no plugin directory, assuming a monolithic charon")
    has_p_cscf = not plugin_dir or os.path.exists(
        os.path.join(plugin_dir, "libstrongswan-p-cscf.so"))
    if has_p_cscf:
        plugins.append("p-cscf")
    else:
        log("warning: charon has no p-cscf plugin, the P-CSCF won't be "
            "requested; pass it to nekoims with -p")
    for p in aka.plugins if plugin_dir else []:
        if not os.path.exists(
                os.path.join(plugin_dir, f"libstrongswan-{p}.so")):
            sys.exit(f"--aka-backend {args.aka_backend} needs the {p} plugin, "
                     f"missing from {plugin_dir}")

    with open(conf, "w") as f:
        f.write(strongswan_conf(vici_socket, plugins, aka, args.loglevel,
                                args.ifname))

    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))
    if WINDOWS:
        signal.signal(signal.SIGBREAK, lambda *_: sys.exit(0))
        tunnel = WintunTunnel(args.ifname, args.mtu)
    else:
        tunnel = Tunnel(args.netns, args.ifname, args.mtu)
    charon = Charon(charon_bin, conf, vici_socket, log_file)
    try:
        aka.start()
        tunnel.create()
        charon.start()
        if WINDOWS:
            tunnel.setup()

        cmd = charon.session()
        remote_auth = args.remote_auth or bundle.get("epdg_auth")
        # Nobody said how the ePDG authenticates: want a certificate, but
        # fall back to EAP-only if that is what it does (e.g. AT&T).
        auth_guessed = remote_auth is None
        remote_auth = remote_auth or "pubkey"
        if remote_auth == "pubkey":
            n = load_cas(cmd, args.ca or ([CA_BUNDLE_DEFAULT]
                                          if CA_BUNDLE_DEFAULT else None))
            log(f"loaded {n} CA certificates")

        def load_conn():
            cmd.load_conn(connection(epdg, identity, args.remote_id or apn,
                                     remote_auth, bundle,
                                     encap=not args.no_encap,
                                     family=args.epdg_family))
        load_conn()

        events = charon.session()
        while True:
            logs = []
            try:
                pcscfs = initiate(cmd, logs)
            except Exception as e:  # vici.exception.CommandException
                log(f"initiate failed: {e}")
                charon.check()
                if auth_guessed and remote_auth == "pubkey" and \
                        any(EAP_ONLY_RE.search(line) for line in logs):
                    log("the ePDG authenticates with EAP only (RFC 5998), "
                        "redialing that way; set \"epdg_auth\": \"eap\" in "
                        "its carrier bundle (or pass --remote-auth eap)")
                    remote_auth = "eap"
                    load_conn()
                    continue
                if not args.retry:
                    sys.exit(1)
                time.sleep(args.retry)
                continue

            vips = local_vips(cmd)
            if bundle.get("pcscf_match_family", False):
                pcscfs = tunnel_family_first(pcscfs, vips)
            if WINDOWS:
                tunnel.configure(vips, pcscfs)
            else:
                tunnel.configure(vips)
            write_state(state_path, {"netns": args.netns,
                                     "ifname": args.ifname,
                                     "vips": vips, "pcscf": pcscfs,
                                     "epdg": epdg, "imsi": imsi})
            write_pcscf(pcscf_path, pcscfs)
            log(f"tunnel up: {args.netns or '-'}/{args.ifname} "
                f"{' '.join(vips)}")
            for p in pcscfs:
                print(f"PCSCF={p}", flush=True)

            # Block until the IKE SA goes away, then redial.
            try:
                wait_down(events)
            except Exception:  # vici connection lost
                charon.check()
                raise
            log("tunnel down")
            tunnel.unconfigure()
            write_state(state_path, None)
            write_pcscf(pcscf_path, None)
            if not args.retry:
                sys.exit(1)
            time.sleep(args.retry)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            for _ in charon.session().terminate({"ike": CONN,
                                                 "timeout": "3000"}):
                pass
        except Exception:
            pass
        charon.stop()
        aka.stop()
        tunnel.destroy()
        write_state(state_path, None)
        write_pcscf(pcscf_path, None)
        for path in (conf, vici_socket):
            if os.path.exists(path):
                os.unlink(path)
        if log_file:
            log_file.flush()


if __name__ == "__main__":
    main()
