#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
dhcp-pcscf: ask the network for the P-CSCF with a stateless DHCPv6
Information-Request (RFC 8415 18.2.6), the alternative to the PCO that
TS 24.229 9.2.1 allows. A test tool, for modems whose firmware loses the
P-CSCF from the PCO.

Requests the SIP server options of RFC 3319 (22 addresses, 21 domain names)
plus DNS servers (23) and the domain search list (24), and prints every
option of the Reply.

    sudo ip netns exec ims python3 tools/dhcp-pcscf.py wwp0s20u10i10

DHCPv6 clients send from a link-local address, which a raw-IP rmnet
interface doesn't have; unless the interface has one, fe80::<IID> (the
interface ID of its global address, as the network assigned it) is added
for the duration and removed again (--no-link-local to skip that and send
from the global address).

Needs root (port 546, adding the address) and iproute2.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import os
import select
import socket
import struct
import subprocess
import sys
import time
import uuid

CLIENT_PORT, SERVER_PORT = 546, 547
ALL_SERVERS = "ff02::1:2"  # All_DHCP_Relay_Agents_and_Servers

INFORMATION_REQUEST, REPLY = 11, 7
OPT_CLIENTID, OPT_SERVERID, OPT_ORO, OPT_ELAPSED_TIME = 1, 2, 6, 8
OPT_STATUS_CODE = 13
OPT_SIP_SERVER_D, OPT_SIP_SERVER_A = 21, 22
OPT_DNS_SERVERS, OPT_DOMAIN_LIST = 23, 24
OPT_INFORMATION_REFRESH_TIME = 32

OPTION_NAMES = {
    OPT_CLIENTID: "client id", OPT_SERVERID: "server id",
    OPT_STATUS_CODE: "status", OPT_SIP_SERVER_D: "sip server domains",
    OPT_SIP_SERVER_A: "sip server addresses (P-CSCF)",
    OPT_DNS_SERVERS: "dns servers", OPT_DOMAIN_LIST: "domain search list",
    OPT_INFORMATION_REFRESH_TIME: "information refresh time",
}


def log(msg: str):
    print(msg, file=sys.stderr, flush=True)


def ip(*args: str, check: bool = True) -> str:
    r = subprocess.run(["ip", *args], capture_output=True, text=True)
    if check and r.returncode:
        sys.exit(f"ip {' '.join(args)}: {r.stderr.strip()}")
    return r.stdout


def addresses(ifname: str) -> list[ipaddress.IPv6Interface]:
    out = json.loads(ip("-6", "-j", "addr", "show", "dev", ifname) or "[]")
    return [ipaddress.IPv6Interface(f"{a['local']}/{a['prefixlen']}")
            for link in out for a in link.get("addr_info", [])]


def option(code: int, data: bytes) -> bytes:
    return struct.pack("!HH", code, len(data)) + data


def information_request(xid: bytes, duid: bytes, elapsed_cs: int) -> bytes:
    oro = struct.pack("!4H", OPT_SIP_SERVER_A, OPT_SIP_SERVER_D,
                      OPT_DNS_SERVERS, OPT_DOMAIN_LIST)
    return (bytes([INFORMATION_REQUEST]) + xid
            + option(OPT_CLIENTID, duid)
            + option(OPT_ORO, oro)
            + option(OPT_ELAPSED_TIME,
                     struct.pack("!H", min(elapsed_cs, 0xFFFF))))


def options(data: bytes):
    while len(data) >= 4:
        code, length = struct.unpack("!HH", data[:4])
        yield code, data[4:4 + length]
        data = data[4 + length:]


def domain_names(data: bytes) -> list[str]:
    """RFC 1035 wire format, uncompressed (RFC 8415 10)."""
    names, labels, i = [], [], 0
    while i < len(data):
        n = data[i]
        i += 1
        if n == 0:
            names.append(".".join(labels))
            labels = []
            continue
        labels.append(data[i:i + n].decode("ascii", "replace"))
        i += n
    if labels:
        names.append(".".join(labels))
    return names


def v6_list(data: bytes) -> list[str]:
    return [str(ipaddress.IPv6Address(data[i:i + 16]))
            for i in range(0, len(data) - 15, 16)]


def describe(code: int, data: bytes) -> str:
    if code in (OPT_SIP_SERVER_A, OPT_DNS_SERVERS):
        return " ".join(v6_list(data))
    if code in (OPT_SIP_SERVER_D, OPT_DOMAIN_LIST):
        return " ".join(domain_names(data))
    if code == OPT_STATUS_CODE and len(data) >= 2:
        return (f"{struct.unpack('!H', data[:2])[0]} "
                f"{data[2:].decode('utf-8', 'replace')}")
    if code == OPT_INFORMATION_REFRESH_TIME and len(data) == 4:
        return f"{struct.unpack('!I', data)[0]}s"
    return data.hex()


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("interface", help="the IMS PDN's interface")
    ap.add_argument("--server", default=ALL_SERVERS,
                    help="where to send it (default %(default)s)")
    ap.add_argument("--timeout", type=float, default=15,
                    help="seconds to retransmit for (default %(default)s)")
    ap.add_argument("--no-link-local", action="store_true",
                    help="don't add a link-local address, send from "
                         "whatever the kernel picks")
    args = ap.parse_args()

    if os.geteuid() != 0:
        sys.exit("must run as root (port 546, adding a link-local address)")
    ifindex = socket.if_nametoindex(args.interface)

    added = None
    addrs = addresses(args.interface)
    if not args.no_link_local and not any(a.is_link_local for a in addrs):
        glob = next((a for a in addrs if a.is_global), None)
        if not glob:
            sys.exit(f"{args.interface} has no global IPv6 address to take "
                     "the interface ID from (--no-link-local to send anyway)")
        iid = int(glob.ip) & ((1 << 64) - 1)
        added = f"{ipaddress.IPv6Address((0xfe80 << 112) | iid)}/64"
        ip("-6", "addr", "add", added, "dev", args.interface, "nodad")
        log(f"{args.interface}: added {added} for the request")

    # DUID-UUID (RFC 6355): the interface has no link-layer address
    duid = struct.pack("!H", 4) + uuid.uuid4().bytes
    xid = os.urandom(3)

    s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
    try:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_BINDTODEVICE,
                     args.interface.encode())
        s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_IF, ifindex)
        s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_HOPS, 1)
        bind = (str(ipaddress.IPv6Interface(added).ip) if added else "::")
        s.bind((bind, CLIENT_PORT, 0, ifindex if added else 0))

        dest = (args.server, SERVER_PORT, 0,
                ifindex if ipaddress.IPv6Address(args.server).is_multicast
                or ipaddress.IPv6Address(args.server).is_link_local else 0)
        start = time.monotonic()
        rt = 1.0  # INF_TIMEOUT, doubling (RFC 8415 7.6, 15)
        reply = None
        while reply is None and time.monotonic() - start < args.timeout:
            elapsed = int((time.monotonic() - start) * 100)
            s.sendto(information_request(xid, duid, elapsed), dest)
            log(f"sent Information-Request to {args.server} "
                f"(xid {xid.hex()})")
            deadline = min(time.monotonic() + rt, start + args.timeout)
            while reply is None:
                left = deadline - time.monotonic()
                if left <= 0 or not select.select([s], [], [], left)[0]:
                    break
                data, peer = s.recvfrom(65535)
                if len(data) < 4 or data[0] != REPLY or data[1:4] != xid:
                    log(f"ignoring {len(data)} bytes from {peer[0]}")
                    continue
                reply = (data, peer)
            rt = min(rt * 2, 3600)
    finally:
        s.close()
        if added:
            ip("-6", "addr", "del", added, "dev", args.interface,
               check=False)

    if reply is None:
        sys.exit(f"no Reply within {args.timeout:.0f}s")
    data, peer = reply
    print(f"Reply from {peer[0]}:")
    pcscfs = []
    for code, value in options(data[4:]):
        name = OPTION_NAMES.get(code, f"option {code}")
        print(f"  {name}: {describe(code, value)}")
        if code == OPT_SIP_SERVER_A:
            pcscfs += v6_list(value)
        elif code == OPT_SIP_SERVER_D:
            pcscfs += domain_names(value)
    print(f"p-cscf: {' '.join(pcscfs) or 'none in the Reply'}")
    sys.exit(0 if pcscfs else 1)


if __name__ == "__main__":
    main()
