#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
mkconfig: generate nekoims.json from the SIM (PC/SC or ModemManager) and a
carrier bundle.

The SIM provides the subscriber identity: IMSI, MNC length (EF.AD), MSISDN
(EF.MSISDN, else a tel:/sip:+ IMPU on the ISIM) and, on a PC/SC card, the
ISIM's IMPI and home domain. ModemManager adds the modem's IMEI. Operator
specifics (IMS domain, transport, headers) come from
carrier-bundles/<digits>.json, picked by the longest IMSI prefix.

With no bundle the operator is run in "standard carrier mode": the 3GPP
discovery names (TS 23.003) are assumed, ePDG
epdg.epc.mncXXX.mccYYY.pub.3gppnetwork.org (which must resolve in DNS) and,
unless the ISIM says otherwise, IMS domain ims.mncXXX.mccYYY.3gppnetwork.org.
If no phone number can be found it is asked for on the terminal.

The P-CSCF changes with every ePDG session, so it is normally passed to
nekoims with -p; --pcscf here stores one in the file instead.

    python3 tools/mkconfig.py [--sim pcsc|mm] -o /etc/nekoims/config.json
    sudo ip netns exec ims ./build/nekoims -p <pcscf>

Needs no root: ModemManager exposes these properties to any user, and pcscd
lets any user talk to the card (unless polkit says otherwise).
"""
from __future__ import annotations

import argparse
import contextlib
import glob
import http.client
import importlib.util
import json
import os
import re
import socket
import sys

MM_BUS = "org.freedesktop.ModemManager1"
MM_PATH = "/org/freedesktop/ModemManager1"
MM_MODEM = "org.freedesktop.ModemManager1.Modem"
MM_SIM = "org.freedesktop.ModemManager1.Sim"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLES_DEFAULT = os.path.join(REPO, "carrier-bundles")
# Loopback TCP where Python has no AF_UNIX (Windows), see simcard-server.
SIMCARD_SERVER_DEFAULT = ("unix:/run/nekoims/simcard.sock"
                          if hasattr(socket, "AF_UNIX")
                          else "http://127.0.0.1:8888")

# Bundle keys copied into nekoims.json as-is.
CONFIG_KEYS = ("domain", "transport", "pcscf_port", "p_access_network_info",
               "contact_features", "expires", "user_agent", "sms",
               "sec_agree", "aka_app", "audio_codecs")

# MCCs in the North American Numbering Plan (+1). They use 3-digit MNCs.
NANP_MCCS = {"302"} | {str(m) for m in range(310, 317)}

ISIM_AID_PREFIX = bytes.fromhex("A0000000871004")

MSISDN_PROMPT = ("NekoIMS could not determine your phone number\r\n"
                 "Please enter it (ex: +18008675309): ")
IMEI_PROMPT = ("NekoIMS could not determine your IMEI\r\n"
               "Please enter the 15-digit IMEI of the device the SIM is in "
               "(dial *#06#): ")


def log(msg: str):
    print(msg, file=sys.stderr)


def mm_prop(path: str, iface: str, name: str):
    from gi.repository import Gio, GLib
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, path, "org.freedesktop.DBus.Properties", "Get",
                      GLib.Variant("(ss)", (iface, name)),
                      GLib.VariantType("(v)"), Gio.DBusCallFlags.NONE,
                      5000, None)
    return v.unpack()[0]


def find_modem(selector: str | None) -> str:
    from gi.repository import Gio
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    v = bus.call_sync(MM_BUS, MM_PATH, "org.freedesktop.DBus.ObjectManager",
                      "GetManagedObjects", None, None, Gio.DBusCallFlags.NONE,
                      5000, None)
    modems = sorted(p for p, ifs in v.unpack()[0].items() if MM_MODEM in ifs)
    if not modems:
        sys.exit("ModemManager reports no modems")
    if selector is None:
        return modems[0]
    for p in modems:
        if (p == selector or p.rsplit("/", 1)[1] == selector or
                mm_prop(p, MM_MODEM, "EquipmentIdentifier") == selector):
            return p
    sys.exit(f"no ModemManager modem matches '{selector}'")


def mm_identity(selector: str | None) -> dict:
    """IMSI, MNC, IMEI and own numbers from ModemManager."""
    from gi.repository import GLib
    try:
        modem = find_modem(selector)
        sim = mm_prop(modem, MM_MODEM, "Sim")
        if not sim or sim == "/":
            sys.exit(f"{modem}: no SIM")
        imsi = mm_prop(sim, MM_SIM, "Imsi")
        mccmnc = mm_prop(sim, MM_SIM, "OperatorIdentifier")
        imei = mm_prop(modem, MM_MODEM, "EquipmentIdentifier")
        own = list(mm_prop(modem, MM_MODEM, "OwnNumbers") or [])
    except GLib.Error as e:
        sys.exit(f"ModemManager: {e.message}")
    if not imsi or not imsi.isdigit():
        sys.exit("ModemManager has no IMSI for this SIM (is it unlocked?)")
    mnc = None
    if mccmnc and mccmnc.startswith(imsi[:3]) and len(mccmnc) in (5, 6):
        mnc = mccmnc[3:]
    return {"where": f"modem {modem}", "imsi": imsi, "mnc": mnc,
            "imei": imei, "numbers": own}


# -- PC/SC -------------------------------------------------------------------

def load_simcard_server():
    """simcard-server/server.py as a module, for its Usim class."""
    path = os.path.join(REPO, "simcard-server", "server.py")
    spec = importlib.util.spec_from_file_location("nekoims_simcard_server",
                                                  path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def tlvs(data: bytes) -> dict:
    """Simple BER-TLV parse (one-byte tags, as in FCPs and ISIM EFs)."""
    out, i = {}, 0
    while i + 1 < len(data):
        tag, n = data[i], data[i + 1]
        i += 2
        if n == 0x81 and i < len(data):
            n, i = data[i], i + 1
        elif n == 0x82 and i + 1 < len(data):
            n, i = int.from_bytes(data[i:i + 2], "big"), i + 2
        out.setdefault(tag, data[i:i + n])
        i += n
    return out


def bcd_number(raw: bytes) -> str:
    digits = ""
    for b in raw:
        for nib in (b & 0x0F, b >> 4):
            if nib == 0x0F:
                return digits
            if nib <= 9:
                digits += str(nib)
    return digits


class PcscSim:
    """Read-only EF access on one PC/SC card, reusing simcard-server's
    Usim for the reader, APDU and application-select plumbing."""

    def __init__(self, reader: int):
        self.mod = load_simcard_server()
        self.usim = self.mod.Usim(reader)
        self.conn = None

    def __enter__(self):
        self.conn = self.usim._connect()
        return self

    def __exit__(self, *exc):
        self.conn.disconnect()

    def select_app(self, prefix: bytes, name: str) -> bool:
        try:
            self.usim._select_app(self.conn, prefix, name)
            return True
        except self.mod.CardError:
            return False

    def _select_ef(self, fid: int) -> dict | None:
        apdu = bytes([0x00, 0xA4, 0x00, 0x04, 0x02]) + \
            fid.to_bytes(2, "big") + b"\x00"
        fcp, sw1, _ = self.usim._xmit(self.conn, apdu)
        if sw1 != 0x90:
            return None
        if fcp[:1] == b"\x62":
            fcp = fcp[2:]
        return tlvs(fcp)

    def read_binary(self, fid: int) -> bytes | None:
        fcp = self._select_ef(fid)
        if fcp is None:
            return None
        size = int.from_bytes(fcp.get(0x80, b"\x00"), "big") or 255
        data = b""
        while len(data) < size:
            off, n = len(data), min(255, size - len(data))
            chunk, sw1, _ = self.usim._xmit(self.conn, bytes(
                [0x00, 0xB0, off >> 8, off & 0xFF, n]))
            if sw1 != 0x90 or not chunk:
                break
            data += chunk
        return data or None

    def read_records(self, fid: int) -> list[bytes]:
        fcp = self._select_ef(fid)
        desc = fcp.get(0x82, b"") if fcp else b""
        if len(desc) < 5:
            return []
        rec_len, count = int.from_bytes(desc[2:4], "big"), desc[4]
        out = []
        for rec in range(1, count + 1):
            data, sw1, _ = self.usim._xmit(self.conn, bytes(
                [0x00, 0xB2, rec, 0x04, rec_len & 0xFF]))
            if sw1 != 0x90:
                break
            out.append(data)
        return out


def isim_strings(data: bytes | None) -> str | None:
    """The 0x80 TLV of an ISIM EF (TS 31.103 4.2.2-4.2.4)."""
    if not data:
        return None
    v = tlvs(data).get(0x80)
    return v.decode("utf-8", "replace").strip() if v else None


def pcsc_identity(reader: int) -> dict:
    """Everything useful on the card: IMSI, MNC length, MSISDN, SPN and the
    ISIM's IMPI, IMPUs and home domain."""
    try:
        sim = PcscSim(reader)
        imsi = sim.usim.imsi()
    except ImportError as e:
        sys.exit(f"PC/SC needs pyscard: {e}")
    except Exception as e:  # pyscard raises a zoo of exception types
        sys.exit(f"cannot read the USIM on PC/SC reader {reader}: {e}")

    ident = {"where": f"PC/SC reader {reader}", "imsi": imsi, "mnc": None,
             "imei": None, "numbers": []}
    try:
        with sim:
            sim.select_app(sim.mod.USIM_AID_PREFIX, "USIM")
            ad = sim.read_binary(0x6FAD)            # EF.AD, TS 31.102 4.2.18
            if ad and len(ad) >= 4 and (ad[3] & 0x0F) in (2, 3):
                ident["mnc"] = imsi[3:3 + (ad[3] & 0x0F)]
            spn = sim.read_binary(0x6F46)           # EF.SPN
            if spn and len(spn) > 1:
                name = spn[1:].split(b"\xff")[0].decode("utf-8", "replace")
                ident["spn"] = name.strip() or None
            for rec in sim.read_records(0x6F40):    # EF.MSISDN
                tail = rec[-14:]
                if len(tail) < 14 or tail[0] in (0, 0xFF) or tail[0] > 11:
                    continue
                digits = bcd_number(tail[2:1 + tail[0]])
                if digits:
                    intl = (tail[1] >> 4) & 0x07 == 1
                    ident["numbers"].append(("+" if intl else "") + digits)
            if sim.select_app(ISIM_AID_PREFIX, "ISIM"):
                ident["impi"] = isim_strings(sim.read_binary(0x6F02))
                ident["home_domain"] = isim_strings(sim.read_binary(0x6F03))
                ident["impus"] = [u for u in map(isim_strings,
                                                 sim.read_records(0x6F04))
                                  if u]
    except Exception as e:
        log(f"warning: reading the SIM files failed ({type(e).__name__}: "
            f"{e}), using the IMSI only")
    return ident


def impu_number(impus: list[str]) -> str | None:
    """+E.164 from a tel: or sip:+...@ IMPU."""
    for u in impus:
        m = re.match(r"(?:tel:|sips?:)(\+\d{6,15})(?:[;@]|$)", u)
        if m:
            return m.group(1)
    return None


# -- running SIM server --------------------------------------------------------

def server_identity(where: str) -> dict:
    """The IMSI from a SIM server that is already running (e.g.
    serial_server.py), plus the IMEI, MSISDN and ISIM identities where it offers
    them; its APDU passthrough can't hold an EF selection across requests."""
    class UnixConn(http.client.HTTPConnection):
        def connect(self):
            self.sock = socket.socket(socket.AF_UNIX)
            self.sock.settimeout(10)
            self.sock.connect(where[len("unix:"):])

    def get(kind: str) -> tuple[int, dict]:
        if where.startswith("unix:"):
            conn = UnixConn("sim")
        else:
            conn = http.client.HTTPConnection(
                re.sub(r"^https?://", "", where).rstrip("/"), timeout=10)
        try:
            conn.request("GET", f"/?type={kind}")
            resp = conn.getresponse()
            return resp.status, json.loads(resp.read() or b"{}")
        finally:
            conn.close()

    try:
        status, body = get("imsi")
    except (OSError, ValueError) as e:
        sys.exit(f"cannot reach the SIM server on {where}: {e}")
    imsi = body.get("imsi")
    if status != 200 or not imsi or not str(imsi).isdigit():
        sys.exit(f"SIM server on {where}: {body.get('error', status)}")
    ident = {"where": f"SIM server {where}", "imsi": imsi, "mnc": None,
             "imei": None, "numbers": []}

    # Extensions of serial_server.py; the other servers answer 400.
    for kind in ("imei", "msisdn", "isim"):
        try:
            status, body = get(kind)
        except (OSError, ValueError):
            continue
        if status != 200:
            if kind == "isim" and status != 400:
                log(f"warning: ISIM not readable: {body.get('error', status)}")
            continue
        if kind == "imei":
            ident["imei"] = body.get("imei")
        elif kind == "msisdn":
            ident["numbers"] = [body["msisdn"]] if body.get("msisdn") else []
        else:
            ident["impi"] = body.get("impi")
            ident["home_domain"] = body.get("domain")
            ident["impus"] = body.get("impu") or []
    return ident


# -- carrier -----------------------------------------------------------------

def find_bundle(imsi: str, bundles_dir: str):
    """The bundle whose digit name is the longest prefix of the IMSI."""
    best, best_len = None, -1
    for path in glob.glob(os.path.join(bundles_dir, "*.json")):
        digits = re.sub(r"\D", "", os.path.splitext(os.path.basename(path))[0])
        if digits and imsi.startswith(digits) and len(digits) > best_len:
            best, best_len = path, len(digits)
    if not best:
        return None, None
    with open(best) as f:
        return json.load(f), os.path.basename(best)


def discovery_epdg(mcc: str, mnc: str) -> str:
    """TS 23.003 19.4.2.4 operator-identifier FQDN of the ePDG."""
    return f"epdg.epc.mnc{mnc.zfill(3)}.mcc{mcc}.pub.3gppnetwork.org"


def resolves(host: str) -> list[str]:
    try:
        infos = socket.getaddrinfo(host, 500, 0, socket.SOCK_DGRAM)
    except (socket.gaierror, UnicodeError):
        return []
    return sorted({i[4][0] for i in infos})


def standard_carrier(imsi: str, mnc: str | None) -> tuple[dict, str]:
    """Standard carrier mode: 3GPP discovery names, if the ePDG resolves.
    Without a known MNC length both are tried, the usual one first."""
    mcc = imsi[:3]
    if mnc:
        candidates = [mnc]
    else:
        lens = (3, 2) if mcc in NANP_MCCS else (2, 3)
        candidates = [imsi[3:3 + n] for n in lens]
    tried = []
    for m in candidates:
        epdg = discovery_epdg(mcc, m)
        addrs = resolves(epdg)
        if addrs:
            log(f"ePDG {epdg} resolves to {', '.join(addrs)}")
            return {
                "name": f"MCC {mcc} / MNC {m} (3GPP discovery)",
                "domain": f"ims.mnc{m.zfill(3)}.mcc{mcc}.3gppnetwork.org",
                "epdg": epdg,
                "apn": "ims",
            }, m
        tried.append(epdg)
    sys.exit(f"no carrier bundle matches IMSI {imsi} and 3GPP ePDG discovery "
             f"failed ({', '.join(tried)} do not resolve). Add a bundle to "
             f"carrier-bundles/ for this operator.")


def e164(number: str, mcc: str) -> str | None:
    digits = re.sub(r"[^\d+]", "", number)
    if re.fullmatch(r"\+\d{6,15}", digits):
        return digits
    if digits.startswith("+"):
        return None
    if mcc in NANP_MCCS:
        if len(digits) == 10:
            return "+1" + digits
        if len(digits) == 11 and digits.startswith("1"):
            return "+" + digits
    return None


def ask_msisdn(mcc: str) -> str | None:
    """Ask on the terminal (the prompt goes to stderr so it never ends up in
    a config written to stdout)."""
    if not sys.stdin.isatty():
        return None
    while True:
        try:
            with contextlib.redirect_stdout(sys.stderr):
                answer = input(MSISDN_PROMPT).strip()
        except EOFError:
            return None
        if not answer:
            return None
        number = e164(answer, mcc)
        if number:
            return number
        log(f"'{answer}' is not an E.164 number, include the country code "
            "(ex: +18008675309)")


def imei_ok(imei: str) -> bool:
    """15 digits with a valid Luhn check digit (TS 23.003 6.2.1)."""
    if not re.fullmatch(r"\d{15}", imei):
        return False
    total = 0
    for i, c in enumerate(reversed(imei)):
        d = int(c) * (2 if i % 2 else 1)
        total += d - 9 if d > 9 else d
    return total % 10 == 0


def ask_imei() -> str | None:
    if not sys.stdin.isatty():
        return None
    while True:
        try:
            with contextlib.redirect_stdout(sys.stderr):
                answer = re.sub(r"[\s/-]", "", input(IMEI_PROMPT))
        except EOFError:
            return None
        if not answer:
            return None
        if imei_ok(answer):
            return answer
        log(f"'{answer}' is not a valid IMEI (15 digits, last one the "
            "check digit)")


def have_pcsc_card() -> bool:
    try:
        from smartcard.System import readers
        for r in readers():
            try:
                c = r.createConnection()
                c.connect()
                c.disconnect()
                return True
            except Exception:
                pass
    except Exception:
        pass
    return False


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--sim", choices=("auto", "pcsc", "mm", "server"),
                    default="auto",
                    help="where the SIM is (default: --reader/--modem if "
                         "given, else a PC/SC card, else ModemManager); "
                         "server asks the running --simcard-server for the "
                         "IMSI only")
    ap.add_argument("--reader", type=int, default=None,
                    help="PC/SC reader index (default: 0)")
    ap.add_argument("--modem", default=None,
                    help="ModemManager modem index, D-Bus path or IMEI "
                         "(default: first modem)")
    ap.add_argument("--pcscf", default=None,
                    help="store this P-CSCF in the file (normally given to "
                         "nekoims with -p instead)")
    ap.add_argument("--msisdn", default=None,
                    help="E.164 number, overrides the SIM's own number")
    ap.add_argument("--imei", default=None,
                    help="IMEI for +sip.instance (default: the modem's; a "
                         "PC/SC reader has none)")
    ap.add_argument("--simcard-server", default=SIMCARD_SERVER_DEFAULT,
                    help=f"(default: {SIMCARD_SERVER_DEFAULT})")
    ap.add_argument("--bundles-dir", default=BUNDLES_DEFAULT)
    ap.add_argument("-o", "--output", default=None,
                    help="write here instead of stdout")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing --output file")
    ap.add_argument("--dialer-args", default=None, metavar="PATH",
                    help="also write strongswan-dialer arguments (ePDG, MNC "
                         "length) here, one per line")
    args = ap.parse_args()

    if args.output and os.path.exists(args.output) and not args.force:
        sys.exit(f"{args.output} exists; pass --force to overwrite it")

    sim = args.sim
    if sim == "auto":
        if args.reader is not None:
            sim = "pcsc"
        elif args.modem is not None:
            sim = "mm"
        else:
            sim = "pcsc" if have_pcsc_card() else "mm"
    if sim == "server":
        ident = server_identity(args.simcard_server)
    elif sim == "pcsc":
        ident = pcsc_identity(args.reader or 0)
    else:
        ident = mm_identity(args.modem)

    imsi = ident["imsi"]
    mcc = imsi[:3]
    mnc = ident["mnc"]

    bundle, source = find_bundle(imsi, args.bundles_dir)
    standard = bundle is None
    mccmnc = str((bundle or {}).get("mccmnc", ""))
    if not mnc and mccmnc.startswith(mcc) and imsi.startswith(mccmnc):
        mnc = mccmnc[3:]
    if standard:
        bundle, mnc = standard_carrier(imsi, mnc)
        source = "standard carrier mode"
        # The ISIM's home domain is what a handset would use.
        if ident.get("home_domain"):
            bundle["domain"] = ident["home_domain"]
    domain = bundle["domain"]

    msisdn = args.msisdn and e164(args.msisdn, mcc)
    if args.msisdn and not msisdn:
        sys.exit(f"--msisdn '{args.msisdn}' is not an E.164 number")
    for n in ident["numbers"]:
        if msisdn:
            break
        msisdn = e164(n, mcc)
        if not msisdn:
            log(f"warning: cannot make SIM number '{n}' E.164")
    if not msisdn:
        msisdn = impu_number(ident.get("impus") or [])
    if not msisdn:
        msisdn = ask_msisdn(mcc)
    if not msisdn:
        log("warning: no MSISDN; calls go out as the registered IMPU, which "
            "operators usually bar when it is IMSI-based")

    # Bundle "identity": "isim" (an operator that provisions the ISIM with
    # its own IMPI/IMPU, e.g. AT&T): those, else IMSI@impi_domain and
    # sip:IMSI@domain, which is what such ISIMs hold. "usim": never the
    # ISIM's, always IMSI@domain and the MSISDN (e.g. Verizon).
    use_isim = standard or bundle.get("identity") == "isim"
    impi = f"{imsi}@{bundle.get('impi_domain', domain)}"
    isim_impi = ident.get("impi")
    if isim_impi and bundle.get("identity") != "usim" and (
            use_isim or isim_impi.endswith("@" + domain)):
        impi = isim_impi
    elif bundle.get("identity") == "isim":
        log(f"warning: ISIM not readable, assuming IMPI {impi}")

    cfg = {"domain": domain}
    if msisdn:
        cfg["msisdn"] = msisdn
    cfg["impi"] = impi
    # Register the ISIM's first SIP IMPU (TS 24.229 5.1.1.1A), as a handset
    # would, unless a bundle says how the operator wants it. Calls still go
    # out as the MSISDN (NekoIMS asserts what P-Associated-URI offers).
    sip_impus = [u for u in ident.get("impus") or []
                 if u.lower().startswith("sip:")]
    if use_isim and sip_impus:
        cfg["impu"] = sip_impus[0]
    elif bundle.get("identity") == "isim":
        cfg["impu"] = f"sip:{imsi}@{domain}"
    if args.pcscf:
        cfg["pcscf"] = args.pcscf
    for key in CONFIG_KEYS:
        if key in bundle and key not in cfg:
            cfg[key] = bundle[key]
    cfg["simcard_server"] = args.simcard_server
    if args.imei and not imei_ok(args.imei):
        sys.exit(f"--imei '{args.imei}' is not a valid 15-digit IMEI")
    imei = args.imei or ident["imei"]
    if imei and not imei_ok(imei):
        log(f"warning: IMEI '{imei}' from the {ident['where']} is not a valid "
            "15-digit IMEI, ignoring it")
        imei = None
    if not imei:
        imei = ask_imei()
    if imei:
        cfg["imei"] = imei
    else:
        log("warning: no IMEI (pass --imei); registering without "
            "+sip.instance, which most operators reject")

    text = json.dumps(cfg, indent=2) + "\n"
    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)),
                    exist_ok=True)
        with open(args.output, "w") as f:
            f.write(text)
        log(f"wrote {args.output}")
    else:
        sys.stdout.write(text)

    dialer = []
    if standard:
        dialer += ["--epdg", bundle["epdg"]]
    if mnc:
        dialer += ["--mnc-len", str(len(mnc))]
    if args.dialer_args:
        with open(args.dialer_args, "w") as f:
            f.write("".join(a + "\n" for a in dialer))

    name = bundle.get("name", "?")
    if ident.get("spn"):
        name += f", SIM says \"{ident['spn']}\""
    log(f"{ident['where']}, IMSI {imsi}, carrier: {name} [{source}]")
    if ident.get("impi") or ident.get("impus"):
        log(f"ISIM: impi={ident.get('impi')} domain={ident.get('home_domain')}"
            f" impu={', '.join(ident.get('impus') or [])}")
    if not args.pcscf:
        log("start nekoims with -p <pcscf> (from the ePDG dialer)")
    if bundle.get("epdg"):
        log(f"ePDG dialer: epdg={bundle['epdg']} apn={bundle.get('apn', 'ims')}"
            f" mcc={mcc} mnc={mnc or '?'}")


if __name__ == "__main__":
    main()
