#!/usr/bin/env python3

# This file is entirely generated by Artificial Intelligence (AI). License may be vague.

"""
qmi_netdev: bring up the internet and IMS PDNs of a Sierra Wireless QMI modem
(EM7455 / Dell DW5811e) on two separate network interfaces, and report the
P-CSCF of the IMS PDN.

    AT!USBCOMP          add rmnet1 next to rmnet0 (the modem reboots once)
    AT+CGDCONT=1,"IPV4V6","<apn_data>"
    AT+CGDCONT=2,"IPV4V6","<apn>"   plus P-CSCF-via-PCO and IM CN flags
    QMI WDS             profile 1 on rmnet0 (internet), profile 2 on rmnet1
                        (IMS), IPv4 and IPv6 each
    P-CSCF              from the QMI settings (IPv4) and AT+CGCONTRDP=2

    sudo python3 tools/qmi_netdev.py
    sudo python3 tools/qmi_netdev.py --netns ims    # IMS interface in a netns

The APNs default to "apn" and "apn_data" of the SIM's carrier bundle (by the
IMSI from AT+CIMI), else "ims" and whatever profile 1 already has.

The interfaces get the addresses the network assigned. The internet one gets
default routes (metric --metric), the IMS one host routes to the P-CSCFs, or
default routes when it is moved into --netns. The P-CSCFs go to
/run/nekoims/pcscf, one per line, which nekoims reads when neither -p nor
"pcscf" in its config is given.

Once the PDNs are up the AT port is no longer needed here, so it is handed to
simcard-server/serial_server.py, which serves the modem's SIM on
/run/nekoims/simcard.sock for nekoims (--no-sim-server to skip), along with
the modem's own number from QMI for mkconfig.

The sessions last as long as the script runs: Ctrl-C stops them and removes
the addresses again. When the modem goes away (suspend/resume) or the network
drops a PDN, everything is torn down, the pcscf file removed, and it is all
brought up again once the modem is back.

QMI goes through qmi-proxy, so it coexists with ModemManager, but nothing
else (NetworkManager) should connect the modem at the same time. The SIM
server needs the AT port to itself: stop ModemManager, or keep it (and the
signal strength it reports) but make it leave that port alone. Needs root,
iproute2, pyserial and libqmi's GObject bindings.
"""
from __future__ import annotations

import argparse
import csv
import glob
import ipaddress
import os
import re
import signal
import subprocess
import sys
import termios
import time

import gi
import serial

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkconfig import BUNDLES_DEFAULT, find_bundle  # noqa: E402

gi.require_version("Qmi", "1.0")
from gi.repository import Gio, GLib, Qmi  # noqa: E402

RUN_DIR = "/run/nekoims"
PCSCF_PATH = os.path.join(RUN_DIR, "pcscf")
SIM_SOCKET = os.path.join(RUN_DIR, "simcard.sock")  # serial_server's default
SIM_SERVER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                          "simcard-server", "serial_server.py")
AT_INTERFACE = 3         # Sierra 9x30 layout: 0 diag, 2 nmea, 3 modem
USBCOMP_RMNET0 = 0x100
USBCOMP_RMNET1 = 0x400
AT_TIMEOUT = 10
QMI_TIMEOUT = 10
DIAL_TIMEOUT = 60        # WDS Start Network waits for the PDN to come up
REBOOT_TIMEOUT = 90      # seconds for the modem to come back after AT!RESET
POLL = 10                # seconds between session checks
RETRY_MIN, RETRY_MAX = 5, 60  # seconds before reconnecting, doubling
SIM_SERVER_TIMEOUT = 60

FINAL_ERROR = re.compile(r"^(ERROR|\+CME ERROR|\+CMS ERROR)", re.I)


class Error(Exception):
    pass


# pyserial raises termios.error (not OSError) once the tty is gone
RETRY_ERRORS = (OSError, serial.SerialException, termios.error, Error,
                GLib.Error)


def log(msg: str):
    print(msg, file=sys.stderr, flush=True)


def ip(*args: str, check: bool = True):
    r = subprocess.run(["ip", *args], capture_output=True, text=True)
    if check and r.returncode:
        raise Error(f"ip {' '.join(args)}: {r.stderr.strip()}")


# -- sysfs --------------------------------------------------------------------

def iface_number(iface_dir: str) -> int:
    with open(os.path.join(iface_dir, "bInterfaceNumber")) as f:
        return int(f.read(), 16)


def driver(path: str) -> str:
    link = os.path.join(path, "driver")
    return os.path.basename(os.readlink(link)) if os.path.islink(link) else ""


def find_modem() -> str:
    """The USB device of the modem: the one with qcserial ports."""
    for tty in sorted(glob.glob("/sys/bus/usb-serial/devices/ttyUSB*")):
        if driver(tty) == "qcserial":
            return os.path.dirname(os.path.dirname(os.path.realpath(tty)))
    raise Error("no qcserial modem found")


def at_port(usbdev: str) -> str:
    for iface in glob.glob(f"{usbdev}/*:*"):
        if iface_number(iface) == AT_INTERFACE:
            for tty in glob.glob(f"{iface}/ttyUSB*"):
                return "/dev/" + os.path.basename(tty)
    raise Error(f"no AT port (interface {AT_INTERFACE}) on {usbdev}")


def qmi_links(usbdev: str) -> list[tuple[str, str]]:
    """(netdev, cdc-wdm path) per qmi_wwan interface, rmnet0 first."""
    links = []
    for iface in glob.glob(f"{usbdev}/*:*"):
        if driver(iface) != "qmi_wwan":
            continue
        nets = os.listdir(os.path.join(iface, "net")) \
            if os.path.isdir(os.path.join(iface, "net")) else []
        wdms = glob.glob(f"{iface}/usbmisc/cdc-wdm*")
        if nets and wdms:
            links.append((iface_number(iface), nets[0],
                          "/dev/" + os.path.basename(wdms[0])))
    return [(n, w) for _, n, w in sorted(links)]


# -- AT port ------------------------------------------------------------------

class AtPort:
    def __init__(self, path: str):
        self.ser = serial.Serial(path, 115200, timeout=0.1)
        for cmd in ("ATE0", "AT+CMEE=2"):
            try:
                self.command(cmd, 2)
            except Error:
                pass

    def close(self):
        try:
            self.ser.close()
        except (OSError, serial.SerialException):
            pass

    def command(self, cmd: str, timeout: float = AT_TIMEOUT) -> list[str]:
        log(f"> {cmd}")
        self.ser.reset_input_buffer()
        self.ser.write((cmd + "\r").encode())
        buf, lines = b"", []
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            buf += self.ser.read(4096)
            while b"\n" in buf:
                raw, buf = buf.split(b"\n", 1)
                line = raw.decode("ascii", "replace").strip()
                if not line or line == cmd:      # blank or echo
                    continue
                log(f"< {line}")
                if line == "OK":
                    return lines
                if FINAL_ERROR.match(line):
                    raise Error(f"{cmd}: {line}")
                lines.append(line)
        raise Error(f"{cmd}: no response within {timeout:.0f}s")


def ensure_usbcomp(usbdev: str) -> str:
    """Make the modem expose rmnet0 and rmnet1; returns its USB device,
    which may have re-enumerated."""
    port = AtPort(at_port(usbdev))
    try:
        port.command('AT!ENTERCND="A710"')
        lines = port.command("AT!USBCOMP?")
        m = next(filter(None, (re.search(r"bitmask:\s*([0-9A-Fa-f]+)", l)
                               for l in lines)), None)
        if not m:
            raise Error("AT!USBCOMP?: no interface bitmask in the response")
        mask = int(m.group(1), 16)
        want = mask | USBCOMP_RMNET0 | USBCOMP_RMNET1
        if mask == want:
            return usbdev
        port.command(f"AT!USBCOMP=1,1,{want:08X}")
        log("USB composition changed, rebooting the modem")
        try:
            port.command("AT!RESET")
        except (OSError, serial.SerialException, Error):
            pass  # the port can vanish before the OK arrives
    finally:
        port.close()

    time.sleep(5)
    deadline = time.monotonic() + REBOOT_TIMEOUT
    while time.monotonic() < deadline:
        try:
            usbdev = find_modem()
            if len(qmi_links(usbdev)) >= 2:
                time.sleep(3)  # let the cdc-wdm nodes settle
                return usbdev
        except (OSError, Error):
            pass
        time.sleep(2)
    raise Error("the modem did not come back with two QMI interfaces "
                f"within {REBOOT_TIMEOUT}s")


def to_ip(text: str) -> str | None:
    """An address from an AT response, IPv6 also in the 27.007
    dotted-decimal form (16 bytes as a.b.c...)."""
    parts = text.split(".")
    if len(parts) == 16 and all(p.isdigit() for p in parts):
        text = str(ipaddress.IPv6Address(bytes(int(p) for p in parts)))
    try:
        addr = ipaddress.ip_address(text)
    except ValueError:
        return None
    return None if addr.is_unspecified else str(addr)


def at_pcscfs(usbdev: str, cid: int) -> list[str]:
    """P-CSCF fields of AT+CGCONTRDP (27.007 10.1.23), one line per family."""
    port = AtPort(at_port(usbdev))
    try:
        lines = port.command(f"AT+CGCONTRDP={cid}")
    except Error as e:
        log(str(e))
        return []
    finally:
        port.close()
    found = []
    for line in lines:
        if not line.startswith("+CGCONTRDP:"):
            continue
        fields = next(csv.reader([line.split(":", 1)[1].strip()]))
        for f in fields[7:9]:
            addr = to_ip(f.strip())
            if addr:
                found.append(addr)
    return found


# -- QMI ----------------------------------------------------------------------

def wait(begin, finish):
    ctx = GLib.MainContext.default()
    box = {}

    def cb(_src, res, _data=None):
        try:
            box["v"] = finish(res)
        except GLib.Error as e:
            box["e"] = e

    begin(cb)
    while not box:
        ctx.iteration(True)
    if "e" in box:
        raise box["e"]
    return box["v"]


def u32_ip(value: int) -> str:
    return str(ipaddress.IPv4Address(value))


def u16_ip(words: list[int]) -> str:
    return str(ipaddress.IPv6Address(b"".join(w.to_bytes(2, "big")
                                              for w in words)))


class Session:
    """One PDN family (IPv4 or IPv6) on one QMI port."""

    def __init__(self, dev, cid: int, family: int):
        self.dev, self.cid, self.family = dev, cid, family
        self.handle = None
        self.wds = wait(lambda cb: dev.allocate_client(
                            Qmi.Service.WDS, 0, QMI_TIMEOUT, None, cb, None),
                        dev.allocate_client_finish)

    @property
    def name(self) -> str:
        return f"CID {self.cid} IPv{self.family}"

    def start(self):
        fam = Qmi.WdsIpFamily.IPV4 if self.family == 4 else Qmi.WdsIpFamily.IPV6
        inp = Qmi.MessageWdsSetIpFamilyInput.new()
        inp.set_preference(fam)
        try:
            wait(lambda cb: self.wds.set_ip_family(inp, QMI_TIMEOUT, None, cb,
                                                   None),
                 self.wds.set_ip_family_finish).get_result()
        except GLib.Error:
            pass  # older firmware; the preference in Start Network suffices
        inp = Qmi.MessageWdsStartNetworkInput.new()
        inp.set_profile_index_3gpp(self.cid)
        inp.set_ip_family_preference(fam)
        out = wait(lambda cb: self.wds.start_network(inp, DIAL_TIMEOUT, None,
                                                     cb, None),
                   self.wds.start_network_finish)
        try:
            out.get_result()
        except GLib.Error as e:
            if e.matches(Qmi.protocol_error_quark(), Qmi.ProtocolError.NOEFFECT):
                log(f"{self.name}: already connected by another client")
                return
            reason = ""
            try:
                vtype, vreason = out.get_verbose_call_end_reason()
                reason = (f" ({Qmi.WdsVerboseCallEndReasonType.get_string(vtype)}"
                          f" {vreason})")
            except GLib.Error:
                pass
            raise Error(f"{self.name}: {e.message}{reason}")
        self.handle = out.get_packet_data_handle()

    def settings(self):
        inp = Qmi.MessageWdsGetCurrentSettingsInput.new()
        inp.set_requested_settings(
            Qmi.WdsRequestedSettings.IP_ADDRESS
            | Qmi.WdsRequestedSettings.GATEWAY_INFO
            | Qmi.WdsRequestedSettings.MTU
            | Qmi.WdsRequestedSettings.PCSCF_SERVER_ADDRESS_LIST)
        out = wait(lambda cb: self.wds.get_current_settings(
                       inp, QMI_TIMEOUT, None, cb, None),
                   self.wds.get_current_settings_finish)
        out.get_result()
        return out

    def connected(self) -> bool:
        out = wait(lambda cb: self.wds.get_packet_service_status(
                       None, QMI_TIMEOUT, None, cb, None),
                   self.wds.get_packet_service_status_finish)
        out.get_result()
        return out.get_connection_status() == Qmi.WdsConnectionStatus.CONNECTED

    def stop(self):
        if self.handle is not None:
            inp = Qmi.MessageWdsStopNetworkInput.new()
            inp.set_packet_data_handle(self.handle)
            try:
                wait(lambda cb: self.wds.stop_network(inp, QMI_TIMEOUT, None,
                                                      cb, None),
                     self.wds.stop_network_finish).get_result()
            except GLib.Error as e:
                log(f"{self.name}: stop: {e.message}")
            self.handle = None
        try:
            wait(lambda cb: self.dev.release_client(
                     self.wds, Qmi.DeviceReleaseClientFlags.RELEASE_CID,
                     QMI_TIMEOUT, None, cb, None),
                 self.dev.release_client_finish)
        except GLib.Error:
            pass


class Link:
    """A PDN (IPv4 and IPv6 sessions) on one rmnet interface."""

    def __init__(self, netdev: str, wdm: str, cid: int):
        self.netdev, self.wdm, self.cid = netdev, wdm, cid
        self.sessions: list[Session] = []
        self.v4 = self.v6 = None
        self.mtu = None
        self.pcscfs: list[str] = []
        f = Gio.File.new_for_path(wdm)
        self.dev = wait(lambda cb: Qmi.Device.new(f, None, cb, None),
                        Qmi.Device.new_finish)
        wait(lambda cb: self.dev.open(Qmi.DeviceOpenFlags.PROXY, QMI_TIMEOUT,
                                      None, cb, None), self.dev.open_finish)

    def mark_ims_profile(self):
        """Ask for the P-CSCF in the PCO and flag the PDN as IMS signalling;
        without this the network sends no P-CSCF."""
        wds = wait(lambda cb: self.dev.allocate_client(
                       Qmi.Service.WDS, 0, QMI_TIMEOUT, None, cb, None),
                   self.dev.allocate_client_finish)
        try:
            inp = Qmi.MessageWdsModifyProfileInput.new()
            inp.set_profile_identifier(getattr(Qmi.WdsProfileType, "3GPP"), self.cid)
            inp.set_pcscf_address_using_pco(True)
            inp.set_imcn_flag(True)
            wait(lambda cb: wds.modify_profile(inp, QMI_TIMEOUT, None, cb,
                                               None),
                 wds.modify_profile_finish).get_result()
        except GLib.Error as e:
            log(f"CID {self.cid}: setting the P-CSCF/IM CN flags: {e.message}")
        finally:
            wait(lambda cb: self.dev.release_client(
                     wds, Qmi.DeviceReleaseClientFlags.RELEASE_CID,
                     QMI_TIMEOUT, None, cb, None),
                 self.dev.release_client_finish)

    def set_raw_ip(self):
        ip("link", "set", self.netdev, "down")
        with open(f"/sys/class/net/{self.netdev}/qmi/raw_ip", "w") as f:
            f.write("Y")
        try:
            wda = wait(lambda cb: self.dev.allocate_client(
                           Qmi.Service.WDA, 0, QMI_TIMEOUT, None, cb, None),
                       self.dev.allocate_client_finish)
            inp = Qmi.MessageWdaSetDataFormatInput.new()
            inp.set_link_layer_protocol(Qmi.WdaLinkLayerProtocol.RAW_IP)
            wait(lambda cb: wda.set_data_format(inp, QMI_TIMEOUT, None, cb,
                                                None),
                 wda.set_data_format_finish).get_result()
            wait(lambda cb: self.dev.release_client(
                     wda, Qmi.DeviceReleaseClientFlags.RELEASE_CID,
                     QMI_TIMEOUT, None, cb, None),
                 self.dev.release_client_finish)
        except GLib.Error as e:
            log(f"{self.wdm}: WDA set data format: {e.message}")

    def up(self):
        self.set_raw_ip()
        errors = []
        for family in (4, 6):
            s = Session(self.dev, self.cid, family)
            try:
                s.start()
                out = s.settings()
            except (Error, GLib.Error) as e:
                errors.append(str(e) if isinstance(e, Error)
                              else f"{s.name}: {e.message}")
                s.stop()
                continue
            self.sessions.append(s)
            if family == 4:
                prefix = bin(out.get_ipv4_gateway_subnet_mask()).count("1")
                self.v4 = f"{u32_ip(out.get_ipv4_address())}/{prefix}"
                try:
                    self.pcscfs += [u32_ip(a) for a in
                                    out.get_pcscf_server_address_list()]
                except GLib.Error:
                    pass
            else:
                words, prefix = out.get_ipv6_address()
                self.v6 = f"{u16_ip(words)}/{prefix}"
            try:
                mtu = out.get_mtu()
                if mtu and (not self.mtu or mtu < self.mtu):
                    self.mtu = mtu
            except GLib.Error:
                pass
        for e in errors:
            log(e)
        if not self.sessions:
            raise Error(f"CID {self.cid}: no IPv4 or IPv6 session came up")
        log(f"{self.netdev}: CID {self.cid} "
            f"{' '.join(filter(None, (self.v4, self.v6)))}")

    def configure(self, routes: list[str], netns: str | None):
        ip("addr", "flush", "dev", self.netdev)
        if netns:
            ip("link", "set", self.netdev, "netns", netns)
        pre = ("-n", netns) if netns else ()
        if self.mtu:
            ip(*pre, "link", "set", self.netdev, "mtu", str(self.mtu))
        if self.v4:
            ip(*pre, "addr", "add", self.v4, "dev", self.netdev)
        if self.v6:
            ip(*pre, "-6", "addr", "add", self.v6, "dev", self.netdev,
               "nodad")
        ip(*pre, "link", "set", self.netdev, "up")
        for r in routes:
            fam = "-6" if ":" in r.split()[0] else "-4"
            ip(*pre, fam, "route", "replace", *r.split(), "dev", self.netdev)

    def check(self):
        for s in self.sessions:
            if s.handle is not None and not s.connected():
                raise Error(f"{self.netdev}: {s.name} was disconnected")

    def down(self, netns: str | None):
        for s in self.sessions:
            s.stop()
        self.sessions = []
        pre = ("-n", netns) if netns else ()
        ip(*pre, "addr", "flush", "dev", self.netdev, check=False)
        ip(*pre, "link", "set", self.netdev, "down", check=False)
        if netns:
            ip("-n", netns, "link", "set", self.netdev, "netns", "1",
               check=False)
        try:
            wait(lambda cb: self.dev.close_async(QMI_TIMEOUT, None, cb, None),
                 self.dev.close_finish)
        except GLib.Error:
            pass


def dms_msisdn(dev) -> str | None:
    """The modem's own number (QMI DMS Get MSISDN). Verizon modules keep the
    MDN in NV, so this can work where the SIM's EF.MSISDN is empty."""
    try:
        dms = wait(lambda cb: dev.allocate_client(
                       Qmi.Service.DMS, 0, QMI_TIMEOUT, None, cb, None),
                   dev.allocate_client_finish)
    except GLib.Error as e:
        log(f"QMI DMS: {e.message}")
        return None
    try:
        out = wait(lambda cb: dms.get_msisdn(None, QMI_TIMEOUT, None, cb,
                                             None),
                   dms.get_msisdn_finish)
        out.get_result()
        return re.sub(r"[^\d+]", "", out.get_msisdn()) or None
    except GLib.Error as e:
        log(f"QMI DMS Get MSISDN: {e.message}")
        return None
    finally:
        try:
            wait(lambda cb: dev.release_client(
                     dms, Qmi.DeviceReleaseClientFlags.RELEASE_CID,
                     QMI_TIMEOUT, None, cb, None),
                 dev.release_client_finish)
        except GLib.Error:
            pass


def default_routes(link: Link, metric: int | None) -> list[str]:
    extra = f" metric {metric}" if metric is not None else ""
    return [r + extra for r, a in (("default", link.v4), ("::/0", link.v6))
            if a]


def write_pcscf(path: str, pcscfs: list[str]):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write("".join(p + "\n" for p in pcscfs))
    os.replace(tmp, path)


class Bearer:
    """Both PDNs, the routes, the pcscf file and the SIM server, brought up
    and torn down as one."""

    def __init__(self, args):
        self.args = args
        self.links: list[Link] = []
        self.sim_server = None
        self.made_netns = False

    def up(self):
        args = self.args
        usbdev = ensure_usbcomp(wait_for_modem())
        port = AtPort(at_port(usbdev))
        try:
            if args.apn is None or args.apn_data is None:
                m = re.search(r"\d{6,15}", " ".join(port.command("AT+CIMI")))
                if not m:
                    raise Error("AT+CIMI: no IMSI in the response")
                imsi = m.group(0)
                bundle, name = find_bundle(imsi, BUNDLES_DEFAULT)
                log(f"IMSI {imsi}: carrier bundle {name or 'none'}")
                bundle = bundle or {}
                if args.apn is None:
                    args.apn = bundle.get("apn", "ims")
                if args.apn_data is None:
                    args.apn_data = bundle.get("apn_data", "")
            if args.apn_data:
                port.command(f'AT+CGDCONT=1,"IPV4V6","{args.apn_data}"')
            port.command(f'AT+CGDCONT=2,"IPV4V6","{args.apn}"')
        finally:
            port.close()

        pairs = qmi_links(usbdev)
        if len(pairs) < 2:
            raise Error(f"expected two QMI interfaces, found {len(pairs)}")
        for (netdev, wdm), cid in zip(pairs, (1, 2)):
            self.links.append(Link(netdev, wdm, cid))
            if cid == 2:
                self.links[-1].mark_ims_profile()
            self.links[-1].up()
        inet, ims = self.links

        pcscfs = ims.pcscfs + [p for p in at_pcscfs(usbdev, 2)
                               if p not in ims.pcscfs]

        inet.configure([] if args.no_default_route
                       else default_routes(inet, args.metric), None)
        if args.netns:
            if args.netns not in subprocess.run(
                    ["ip", "netns", "list"], capture_output=True,
                    text=True).stdout.split():
                ip("netns", "add", args.netns)
                self.made_netns = True
            ims.configure(default_routes(ims, None), args.netns)
        else:
            ims.configure([p for p in pcscfs
                           if (":" in p and ims.v6) or
                           (":" not in p and ims.v4)], None)

        print(f"internet: {inet.netdev} "
              f"{' '.join(filter(None, (inet.v4, inet.v6)))}")
        print(f"ims:      {ims.netdev} "
              f"{' '.join(filter(None, (ims.v4, ims.v6)))}"
              + (f" (netns {args.netns})" if args.netns else ""))
        print(f"p-cscf:   {' '.join(pcscfs) or 'none found'}", flush=True)

        # The SIM server first: nekoims starts as soon as the pcscf file
        # appears, and needs the SIM right away.
        if not args.no_sim_server:
            self.start_sim_server(at_port(usbdev), dms_msisdn(inet.dev))
        if pcscfs:
            write_pcscf(PCSCF_PATH, pcscfs)

    def start_sim_server(self, port: str, msisdn: str | None):
        self.sim_server = subprocess.Popen(
            [sys.executable, SIM_SERVER, "--port", port]
            + (["--msisdn", msisdn] if msisdn else []))
        deadline = time.monotonic() + SIM_SERVER_TIMEOUT
        while not os.path.exists(SIM_SOCKET):
            if self.sim_server.poll() is not None:
                raise Error(f"serial_server.py exited "
                            f"({self.sim_server.returncode})")
            if time.monotonic() > deadline:
                raise Error(f"serial_server.py did not listen on "
                            f"{SIM_SOCKET} within {SIM_SERVER_TIMEOUT}s")
            time.sleep(0.2)

    def check(self):
        for link in self.links:
            link.check()
        if self.sim_server and self.sim_server.poll() is not None:
            raise Error(f"serial_server.py exited "
                        f"({self.sim_server.returncode})")

    def down(self):
        if os.path.exists(PCSCF_PATH):
            os.unlink(PCSCF_PATH)
        if self.sim_server and self.sim_server.poll() is None:
            self.sim_server.terminate()
            try:
                self.sim_server.wait(5)
            except subprocess.TimeoutExpired:
                self.sim_server.kill()
        self.sim_server = None
        for link in self.links:
            link.down(self.args.netns if link.cid == 2 else None)
        self.links = []


def wait_for_modem() -> str:
    """The modem's USB device, once it is there (again) with its AT port."""
    waited = False
    while True:
        try:
            usbdev = find_modem()
            at_port(usbdev)
            if qmi_links(usbdev):
                break
        except (OSError, Error):
            pass
        if not waited:
            log("waiting for the modem")
            waited = True
        time.sleep(2)
    if waited:
        time.sleep(5)  # let it finish enumerating and booting
    return usbdev


def describe(e: Exception) -> str:
    return f"QMI error: {e.message}" if isinstance(e, GLib.Error) else str(e)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--apn",
                    help="IMS APN, CID 2 (default: the carrier bundle's "
                         "\"apn\", else ims)")
    ap.add_argument("--apn-data",
                    help="internet APN, CID 1 (default: the carrier bundle's "
                         "\"apn_data\", else profile 1 is left as it is)")
    ap.add_argument("--metric", type=int, default=700,
                    help="metric of the internet default routes, so they "
                         "don't take over from Wi-Fi/Ethernet "
                         "(default %(default)s)")
    ap.add_argument("--no-default-route", action="store_true",
                    help="no default routes on the internet interface")
    ap.add_argument("--netns",
                    help="move the IMS interface into this netns (created "
                         "if missing) with default routes there")
    ap.add_argument("--no-sim-server", action="store_true",
                    help="don't run serial_server.py on the AT port")
    args = ap.parse_args()

    if os.geteuid() != 0:
        sys.exit("must run as root: qmi-proxy only accepts root clients")
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    bearer = Bearer(args)
    delay = RETRY_MIN
    try:
        while True:
            try:
                bearer.up()
                delay = RETRY_MIN
                log("up; Ctrl-C to disconnect")
                while True:
                    time.sleep(POLL)
                    bearer.check()
            except RETRY_ERRORS as e:
                # Typically suspend/resume: the modem drops off the bus and
                # comes back, or the network drops the PDNs meanwhile.
                log(f"qmi_netdev: {describe(e)}; reconnecting in {delay}s")
                bearer.down()
                time.sleep(delay)
                delay = min(delay * 2, RETRY_MAX)
    except KeyboardInterrupt:
        pass
    finally:
        bearer.down()
        if bearer.made_netns:
            ip("netns", "del", args.netns, check=False)


if __name__ == "__main__":
    main()
